# -*- coding: utf-8 -*-
# BARCELONA — one deep guide + a full portal hub (no separate stay/do/around articles yet,
# so the hub itself has to carry all of that). All specifics from research/city-barcelona.md
# (July 2026 research pass). Honest caveats kept in — overtourism, August closures, paella.

CITY = {
 "id": "barcelona",
 "intro_blocks": [
  {"t":"lead","html":"Barcelona has two menus. There's the one taped to a window on La Rambla, in six languages, next to a photo of paella and a tout holding laminated pages — and there's the one three streets back, chalked on a board, in Catalan only, where the vermut is on tap and nobody's translated anything for you. This guide is about finding the second one."},
  {"t":"p","html":"The real Barcelona eats late, drinks vermut before lunch on weekends, and rarely leaves its own neighborhood to do either. Tapas bars, wine bodegas and vermuterías cluster in Sant Andreu, Gràcia and the back lanes of El Born and El Raval — a few metro stops from the postcard sights, and a different city entirely. Here are the places we'd actually take a friend, starting with the one that's been open since 1820."},
  {"t":"eats","ranked":True,"items":[
    {"name":"Bar Marsella","slug":"bar-marsella","area":"El Raval","blurb":"Barcelona's most storied bar, open since 1820 — the original 19th-century interior is still there, and the regulars' list reportedly ran through Picasso, Dalí and Hemingway. Order the house absinthe."},
    {"name":"Vermuteria Oxiterraneo","slug":"vermuteria-oxiterraneo","area":"Sant Andreu","blurb":"The highest-rated pick in this whole guide. House vermouth, ceviche and 'gambas borrachas' (drunken prawns), in a neighborhood most visitors never reach."},
    {"name":"Bodega del Born","slug":"bodega-del-born","area":"El Born","blurb":"A brick-walled wine bar down a Born side street — anchovies with strawberry jam, and a vermouth flight served 'in order of complexity.'"},
    {"name":"Bodega Oliva","slug":"bodega-oliva","area":"Barri Gòtic","blurb":"One street back from La Rambla and a different world: a tiny room where staff build you a tasting menu on request. Ask for the eggplant with goat cheese."},
    {"name":"Bodega Marín","slug":"bodega-marin","area":"Gràcia","blurb":"Owner-run by Vanessa and Luis, fast and unpretentious — reviewers keep noting how easy it is to eat solo at the bar here."},
    {"name":"La Taberna de la Barceloneta","slug":"la-taberna-de-la-barceloneta","area":"Barceloneta","blurb":"Steps from the beach neighborhood: octopus 'bomba' and a paella that actually earns its socarrat crust."},
    {"name":"Comida de Olla","slug":"comida-de-olla","area":"Horta-Guinardó","blurb":"Seafood and black paella worth a detour mid-sightseeing, between Park Güell and Sagrada Família."},
  ]},
  {"t":"h2","text":"Where to stay"},
  {"t":"p","html":"Home base matters more than usual here. The old-town core — Barri Gòtic, El Born, El Raval — puts you inside walking distance of almost everything; Eixample and Barceloneta trade a short metro ride for wider streets, quieter nights or beach access. A spread across budgets, all currently bookable:"},
  {"t":"stays","items":[
    {"name":"Hostal Santa Ana","area":"Barri Gòtic","program":"booking","query":"Hostal Santa Ana Barcelona",
     "blurb":"Central and historic-core, Booking-rated 7.6/10 — the reliable budget pick a few streets from the cathedral."},
    {"name":"Praktik Èssens","area":"Eixample · Passeig de Gràcia","band":"$188","program":"booking","query":"Praktik Essens Barcelona",
     "blurb":"Design-hotel feel right by Gaudí's Passeig de Gràcia landmarks. Rated 9.0/10."},
    {"name":"Acta Voraport","area":"Sant Martí · Poblenou","band":"$157","program":"booking","query":"Acta Voraport Barcelona",
     "blurb":"A 10-minute walk to Bogatell Beach, with a terrace and parking — the pick if you want beach over old-town."},
    {"name":"Yurbban Passage Hotel & Spa","area":"Ciutat Vella","band":"$305","program":"booking","query":"Yurbban Passage Hotel Barcelona",
     "blurb":"An outdoor pool and spa tucked into the old-town center. Rated 9.1/10 — our boutique pick."},
    {"name":"Mandarin Oriental Barcelona","area":"Eixample · Passeig de Gràcia","band":"$938","program":"booking","query":"Mandarin Oriental Barcelona",
     "blurb":"If budget is genuinely open, this is the flagship luxury address on Passeig de Gràcia."},
  ]},
  {"t":"book","head":"Compare Barcelona stays","html":"Booking.com has the deepest Barcelona inventory, real guest ratings and free cancellation on most rooms — good for weighing old-town against Eixample against beachside before you commit.","program":"booking","query":"Barcelona","label":"See Barcelona hotels on Booking"},
  {"t":"h2","text":"What to do"},
  {"t":"p","html":"You could fill a week with sights alone. These are the six worth your time — including the two you need to book before you land, not after."},
  {"t":"do","items":[
    {"name":"Sagrada Família","tag":"Book this first","blurb":"Gaudí's unfinished basilica is the single most-visited monument in Spain. Timed entry regularly sells out days ahead — this is the one to sort before you land.","program":"gyg","query":"Sagrada Familia skip the line Barcelona","label":"See Sagrada Família tickets"},
    {"name":"Park Güell","tag":"Also book ahead","blurb":"Gaudí's mosaic park has capped entry to the monumental zone — around 800 visitors an hour — since 2013. Same rule: reserve the timed slot in advance.","program":"gyg","query":"Park Guell tickets Barcelona","label":"See Park Güell tickets"},
    {"name":"Gothic Quarter walking","tag":"Free, self-guided","blurb":"Roman walls, the cathedral, Plaça Reial, tangled medieval lanes. Best on foot, best early morning or after dinner once the day-trip crowds thin out."},
    {"name":"Montjuïc","tag":"Views","blurb":"The hilltop park and fortress above the port — castle, the Joan Miró Foundation, Magic Fountain shows at night, and a cable car for the views.","program":"gyg","query":"Montjuic cable car Barcelona","label":"See Montjuïc tours"},
    {"name":"La Boqueria","tag":"Go early","blurb":"The famous market off La Rambla is genuinely worth it — if you go early morning, while it's still a working market and not mostly a photo line."},
    {"name":"Montserrat","tag":"Day trip","blurb":"A jagged mountain monastery about an hour out by train and rack railway or cable car, home to the Black Madonna and a centuries-old boys' choir. The best reason to leave the city for a day.","program":"gyg","query":"Montserrat day trip Barcelona","label":"See Montserrat day trips"},
  ]},
  {"t":"book","head":"Book skip-the-line tickets before you land","html":"Sagrada Família and Park Güell aren't 'buy at the door' anymore — both routinely sell out days ahead in high season. GetYourGuide is the easiest way to lock in a timed slot for either, or both, in one place.","program":"gyg","query":"Sagrada Familia Barcelona","label":"Book Sagrada Família & Park Güell tickets"},
  {"t":"h2","text":"Getting around"},
  {"t":"ul","items":[
    "<strong>El Prat airport</strong> — Josep Tarradellas Barcelona–El Prat, about 15km southwest of the center and one of Europe's busiest (57.5 million passengers in 2025). Most flights use Terminal 1.",
    "<strong>Aerobús</strong> — the dedicated express bus from T1/T2 to Plaça Catalunya, roughly €6–7 one-way and about 35–40 minutes, running every 5–20 minutes depending on the time of day.",
    "<strong>Train alternative</strong> — the R2 Nord rail line also connects the airport to Barcelona-Sants and Passeig de Gràcia. Cheaper than the Aerobús, less frequent.",
    "<strong>T-casual card</strong> — the current multi-trip metro/bus card, good for 10 journeys and shareable between however many of you are traveling. Zone 1 covers essentially every sight in this guide; buy it at any metro machine and check the current price there, since fares move.",
    "<strong>On foot</strong> — the old-town core (Gòtic, Born, Raval, Eixample-Dreta) is flat and walkable. Notice that most of the places in our eats list above sit outside that core — Sant Andreu, Horta-Guinardó, Sants, Gràcia. That's the point: a short metro ride buys real neighborhood food over Rambla-adjacent tourist pricing.",
  ]},
  {"t":"p","html":"Two more things worth sorting before you land: a data eSIM so you're online from the airport, and proper travel insurance if you don't already carry annual cover."},
  {"t":"btnrow","btns":[
     {"program":"airalo","query":"spain","label":"Get a Spain eSIM (Airalo)"},
     {"program":"safetywing","label":"Travel insurance (SafetyWing)","style":"btn-forest"},
  ]},
  {"t":"tip","head":"Best time to visit","html":"May–June and September–October are the sweet spot — warm, without August's peak heat or crowds. Barcelona's holiday season really runs six months, May to October, with August daytime temperatures around 27–31°C; winters are mild, with the thinnest crowds and lowest prices. One honest catch: August is also when a lot of the small, family-run bodegas in this guide close for a few weeks — check hours before building a trip around any single one."},
  {"t":"callout","head":"Traveling considerately in Barcelona","html":"This isn't abstract here. By 2017, surveys found roughly 60% of Barcelona residents felt the city had reached or exceeded what it could handle from tourism, and housing pressure from short-term rentals has been severe enough that the city has moved to phase out short-term tourist-apartment licenses. Park Güell's visitor cap and active limits on cruise arrivals are part of the same response. None of that means don't come — it means come a little differently: book a hotel rather than a short-term rental where you can, treat the residential streets around Park Güell and the Gòtic's courtyards as someone's home rather than a backdrop, and spend where this guide already points you — Sant Andreu, Gràcia, Horta-Guinardó — rather than only on the Rambla corridor. It's a better trip anyway."},
 ],
 "faq": [
  ("How many days do you need in Barcelona?",
   "Three full days covers the Gaudí landmarks, the old town, and one proper meal in a couple of neighborhoods. Five to seven is better if you want to add Montserrat, a beach day in Barceloneta, and time to actually sit still at vermut hour instead of rushing it."),
  ("What's the best time of year to visit Barcelona?",
   "May–June or September–October — warm and mostly crowd-free, without August's heat spike or the small-business closures that come with it. Winters are mild, quiet and cheap if you don't need beach weather."),
  ("Where do locals in Barcelona actually eat and drink?",
   "Mostly outside the postcard core — Sant Andreu, Gràcia, and the back lanes of El Born and El Raval, over tapas and a vermut rather than a Rambla-front menú turístico. Our <a class='inline' href='/barcelona/where-to-eat-in-barcelona/'>full food and drink guide</a> has the specific places."),
 ],
}

PAGES = [

# ============================================================ WHERE TO EAT & DRINK
{
 "city":"barcelona", "slug":"where-to-eat-in-barcelona", "order":1,
 "title":"Where to Eat & Drink in Barcelona Like a Local",
 "kicker":"Barcelona · Food",
 "dek":"Past the Rambla's menús turísticos: the tapas bars, vermuterías and century-old bodegas where Barcelona actually eats — plus what to order, and where not to bother.",
 "description":"Where to eat and drink in Barcelona like a local: tapas bars and vermuterías in Sant Andreu and Gràcia, what to order, and the Rambla traps to skip.",
 "read":"12 min", "updated":"July 2026",
 "related":[],
 "blocks":[
  {"t":"lead","html":"Ask a Barcelona local where to eat and you will not hear La Rambla mentioned once. This is the guide to the other city — the one with vermouth on tap, anchovies on toast, and a bar that's been pouring absinthe since 1820."},
  {"t":"p","html":"The tourist-menu stretch — La Rambla, the Gòtic's main drag, anywhere with a tout holding laminated photos of paella — is almost never where you want to eat. The real scene is a short metro ride into Sant Andreu, Gràcia, Sants and the quieter lanes of El Born and El Raval: small bars, family-run bodegas and vermuterías where the menu is in Catalan and nobody's translated it for you. That's where this list lives."},
  {"t":"callout","head":"Start here: Bar Marsella","html":"Barcelona's most storied bar has been pouring drinks since <strong>1820</strong> — the original 19th-century interior is still intact, marble-topped tables and all, in the heart of El Raval. Regulars over the decades reportedly included Picasso, Dalí and Hemingway. Yes, it's on every list now, including this one — but it earned that. Order the house absinthe the old way, over a sugar cube, and take your time with it."},
  {"t":"h2","text":"What to order"},
  {"t":"p","html":"Barcelona's plate is Catalan and Mediterranean first, with a couple of borrowed classics in the mix. Here's what to actually order:"},
  {"t":"ul","items":[
    "<strong>Tapas</strong> — the default way to eat out: small shared plates, leaning Catalan/Mediterranean rather than classic Andalusian bar-tapas style.",
    "<strong>Pa amb tomàquet</strong> — bread rubbed with ripe tomato, olive oil and salt. The everyday table staple, and the truest 'when in Barcelona' bite there is.",
    "<strong>Patatas bravas</strong> — fried potatoes with spicy tomato sauce and garlic alioli. Every bar has an opinion on whose is best; that rivalry is half the fun.",
    "<strong>Jamón</strong> — cured ham, ibérico or serrano, sliced to order from the corner bodega to La Boqueria itself.",
    "<strong>Escalivada</strong> — smoky roasted eggplant, pepper and onion, dressed simply. A quiet highlight on most menus.",
    "<strong>Crema catalana</strong> — Catalonia's own torched-sugar custard, the local answer to crème brûlée (and older than it).",
    "<strong>Vermút</strong> — less a dish than a ritual. More on that below.",
  ]},
  {"t":"tip","head":"Fer el vermut — the Barcelona ritual","html":"On Saturday or Sunday around midday, locals don't do brunch — they do <strong>vermut</strong>: house vermouth on tap, poured over ice with a twist, with a few olives or anchovies on the side, usually before lunch rather than instead of it. Three spots on this list are built entirely around it: Vermuteria Oxiterraneo and Vermuteria Puigmartí below, plus <strong>La Vermuteria del Tano</strong> in Gràcia — a genuine hole-in-the-wall, always busy, standing room only. Go early, or wait."},
  {"t":"callout","head":"About the paella","html":"Worth knowing before you order it: <strong>paella is Valencian, not Catalan</strong> — a dish Barcelona serves well (and has its own noodle cousin of, <em>fideuà</em>) but didn't invent. That's not a red flag on its own, but a restaurant whose whole identity is 'paella + sangria + a tout on the pavement' is usually optimized for footfall, not flavor. If you want it anyway, La Taberna de la Barceloneta below does a version with a proper socarrat crust."},
  {"t":"h2","text":"Fifteen places worth crossing town for"},
  {"t":"p","html":"Ranked by a blend of rating, how often a place comes up unprompted in reviews, and plain travel-guide value — not just star count. Bar Marsella tops it on story alone; the rest earn their spot on food."},
  {"t":"eats","ranked":True,"items":[
    {"name":"Bar Marsella","slug":"bar-marsella","area":"El Raval","blurb":"The 1820 original. Order the house absinthe and sit with it — the one place on this list that's also a piece of the city's history."},
    {"name":"Vermuteria Oxiterraneo","slug":"vermuteria-oxiterraneo","area":"Sant Andreu","blurb":"The highest-rated stop on this whole list. House vermouth, ceviche and 'gambas borrachas' (drunken prawns), in a neighborhood most guidebooks skip entirely."},
    {"name":"Bodega del Born","slug":"bodega-del-born","area":"El Born","blurb":"Brick walls, a vermouth flight served 'in order of complexity,' and an unlikely but genuinely great pairing: anchovies with strawberry jam."},
    {"name":"Restaurant l'Andreuenc","slug":"restaurant-landreuenc","area":"Sant Andreu","blurb":"Two brothers running traditional Catalan cooking, menú del día around €18. Reserve ahead — word's out."},
    {"name":"Chez Lola","slug":"chez-lola","area":"Sant Andreu","blurb":"A French bistro with a €12.90 weekday menú del día. The mustard chicken and the homemade banana-chocolate cake are the two dishes people specifically come back for."},
    {"name":"La Taberna de la Barceloneta","slug":"la-taberna-de-la-barceloneta","area":"Barceloneta","blurb":"Octopus 'bomba' and a paella with a proper socarrat crust, a few streets from the sand."},
    {"name":"Bodegón Club","slug":"bodegon-club","area":"Sants","blurb":"Mezcal, focaccia, and live poetry or music some nights — 'tapas with soul,' per its own regulars."},
    {"name":"Comida de Olla","slug":"comida-de-olla","area":"Horta-Guinardó","blurb":"Seafood and black paella good enough that people detour here specifically, mid-sightseeing between Park Güell and Sagrada Família."},
    {"name":"Bodega Oliva","slug":"bodega-oliva","area":"Barri Gòtic","blurb":"One street off La Rambla and a completely different experience: a tiny room where staff will build you a tasting menu on request. Ask for the eggplant with goat cheese."},
    {"name":"El Cullerot de Sants","slug":"el-cullerot-de-sants","area":"Sants","blurb":"Menu written only in Catalan, priced like a neighborhood canteen. Chickpeas with pork cheek and alioli is the dish everyone mentions."},
    {"name":"La Platilleria","slug":"la-platilleria","area":"Poble-sec","blurb":"Market-driven small plates with a real neighborhood feel, away from the Montjuïc crowds."},
    {"name":"Celler Cal Marino","slug":"celler-cal-marino","area":"Poble-sec","blurb":"A working wine cellar — buy a bottle straight from the barrel, or just take a glass with a pincho at the counter."},
    {"name":"Bodega Marín","slug":"bodega-marin","area":"Gràcia","blurb":"Owner-run by Vanessa and Luis. Fast kitchen, and reviewers keep singling out how comfortable it is to eat solo at the bar."},
    {"name":"Vermuteria Puigmartí","slug":"vermuteria-puigmarti","area":"Gràcia","blurb":"Home of 'patates Puigmartí' — boiled, not fried, with house sauces. One reviewer summed it up as 'CERO comercial y turístico.'"},
    {"name":"Xocolateria La Nena","slug":"xocolateria-la-nena","area":"Gràcia","blurb":"Old-school hot chocolate and churros, thick enough to stand a spoon in, plus pa amb tomàquet. The most-reviewed café on this whole list."},
  ]},
  {"t":"h2","text":"Where to eat, neighborhood by neighborhood"},
  {"t":"p","html":"A few of these neighborhoods carry most of the list above. Here's what each one is actually like."},
  {"t":"h3","text":"Sant Andreu"},
  {"t":"p","html":"Tied with Gràcia for the most-represented neighborhood on this list, and maybe the most convincing argument that Barcelona's best food isn't in the center at all. Vermuteria Oxiterraneo, Restaurant l'Andreuenc and Chez Lola are all here — a solid metro ride north of the Gòtic, genuinely residential, genuinely unbothered by tourism."},
  {"t":"h3","text":"Gràcia"},
  {"t":"p","html":"The other neighborhood carrying this list, and the least touristy of the central districts — a former village annexed into the city in 1897 that still feels like one, all small plazas and independent shops. Bodega Marín, Vermuteria Puigmartí and Xocolateria La Nena sit within a few blocks of each other here."},
  {"t":"h3","text":"El Born"},
  {"t":"p","html":"Chic-medieval, and more polished than its neighbor the Gòtic — the Picasso Museum and Santa Maria del Mar basilica sit alongside boutique shopping and Bodega del Born's brick-walled bar."},
  {"t":"h3","text":"El Raval"},
  {"t":"p","html":"Barcelona's grittiest, most multicultural central district: the MACBA contemporary art museum, an edgy bar scene, and Bar Marsella. Improving unevenly — genuinely rough in patches, genuinely worth it for the right bar."},
  {"t":"compare","head":["Neighborhood","The vibe","Watch for"],
   "rows":[
     ["<strong>Sant Andreu</strong>","Residential, unbothered by tourism, the strongest food-per-block ratio on this list","Further from the center — budget a proper metro ride"],
     ["<strong>Gràcia</strong>","Bohemian former village, small plazas, the least touristy central district","Popular with locals on weekend nights — some spots fill fast"],
     ["<strong>El Born</strong>","Chic-medieval, boutique shopping alongside genuinely good bars","More polished, and pricier, than its neighbor the Gòtic"],
     ["<strong>El Raval</strong>","Gritty, multicultural, an edgy bar scene including Bar Marsella","Genuinely rough in patches — stick to busy, well-lit streets at night"],
     ["<strong>Barri Gòtic</strong>","Medieval core, atmospheric early morning or late evening","The main tourist trap by day — the closer to La Rambla, the worse the menu"],
   ],
   "cap":"Rule of thumb: the further your table is from La Rambla, the better the meal."},
  {"t":"h2","text":"Markets: Boqueria vs. the real ones"},
  {"t":"p","html":"La Boqueria, off La Rambla, is the famous one — and it's genuinely worth seeing, just go early morning before the tour groups arrive, while it's still a working market rather than a photo line. For markets locals actually shop at, look to <strong>Mercat de Sant Antoni</strong> and <strong>Mercat de la Barceloneta</strong> — no polish, no crowd, just the neighborhood buying dinner."},
  {"t":"book","head":"Want someone to walk you through it?","html":"A guided tapas-and-vermut crawl through the Born and the Gòtic is one of the better ways to taste your way through several of these styles in one evening, especially on a first trip when you don't yet know which bar does what.","program":"gyg","query":"Barcelona tapas and vermut tour","label":"Find a tapas & vermut tour"},
  {"t":"warn","head":"Check hours in August","html":"Several of the family-run bodegas on this list close for a few weeks in August, along with much of small-business Barcelona. If you're building a trip around one specific place from this guide, check its current hours before you go — don't just trust this page."},
 ],
 "faq":[
   ("What's the best neighborhood in Barcelona for real local food?",
    "Sant Andreu, tied with Gràcia — both are genuinely residential, barely touched by tourism, and between them carry most of this guide's list. Sant Andreu sits further out; Gràcia is closer in and just as local."),
   ("What is vermut and when do locals drink it?",
    "Vermút is Barcelona's Saturday/Sunday midday ritual — house vermouth on tap with olives or anchovies, usually before lunch rather than instead of it. Vermuteria Oxiterraneo and Vermuteria Puigmartí, both on this list, are built entirely around it."),
   ("Is paella actually a Catalan dish?",
    "No — it's Valencian in origin. Barcelona serves plenty of good paella (and its noodle cousin, fideuà), but it's a borrowed dish, not a local invention. A restaurant selling almost nothing else, right on La Rambla, is usually the tourist-trap tell, not a paella specialist."),
 ],
},

]
