# -*- coding: utf-8 -*-
# BARCELONA — three deeper guides that extend barcelona.py's hub: where to stay,
# what to do, and a 3-day itinerary. No CITY block here — barcelona.py already
# owns the hub (intro_blocks, FAQ); this file only adds PAGES. All specifics from
# research/city-barcelona.md (July 2026 pass). Same honesty rules as the rest of
# the network: no invented hotels, prices, or ratings — only researched facts and
# well-established Barcelona general knowledge.

PAGES = [

# ============================================================ WHERE TO STAY
{
 "city":"barcelona", "slug":"where-to-stay-in-barcelona", "order":2,
 "title":"Where to Stay in Barcelona: Best Areas & Hotels",
 "kicker":"Barcelona · Where to stay",
 "dek":"Six neighborhoods, six different trips. Here's who each one actually suits, and exactly which hotels to book in every price range.",
 "description":"Where to stay in Barcelona: an honest, area-by-area guide to Barri Gòtic, El Born, Gràcia, Eixample, Barceloneta & El Raval, with real hotels.",
 "read":"8 min", "updated":"July 2026",
 "related":["where-to-eat-in-barcelona","best-things-to-do-in-barcelona","3-days-in-barcelona"],
 "blocks":[
  {"t":"lead","html":"Barcelona's center isn't one neighborhood, it's six stitched together — and where you sleep decides whether your trip is medieval lanes and cathedral bells or wide Eixample boulevards a block from Gaudí. Here's who each area actually suits, and exactly which hotels to book in each."},
  {"t":"h2","text":"The six neighborhoods, honestly"},
  {"t":"p","html":"Skip the generic 'stay central' advice — in Barcelona, 'central' means at least six different things depending on what kind of trip you want."},
  {"t":"compare","head":["Area","Best for","The trade-off"],
   "rows":[
     ["<strong>Barri Gòtic</strong>","First-timers who want to walk to everything","Touristy by day; only really atmospheric early morning or after dinner"],
     ["<strong>El Born</strong>","Old-town charm with more polish","Pricier than the Gòtic next door, and just as busy on weekend nights"],
     ["<strong>El Raval</strong>","Nightlife, art, lower prices","Genuinely rough in patches — stick to the busier streets after dark"],
     ["<strong>Gràcia</strong>","A local, bohemian feel; longer stays","A short walk or metro ride out from the marquee sights"],
     ["<strong>Eixample</strong>","Space, the Gaudí landmarks, shopping, the Gaixample LGBTQ+ scene","Wide grid streets feel more 'city' than 'old town'"],
     ["<strong>Barceloneta</strong>","Beach access, seafood","Touristy and can feel rowdy right on the sand"],
   ],
   "cap":"If you only take one thing from this page: first trip, want to walk everywhere → Barri Gòtic or El Born. Want Gaudí on your doorstep → Eixample."},
  {"t":"h2","text":"Budget: hostels and simple stays"},
  {"t":"p","html":"Barcelona doesn't have the sprawling backpacker scene of some cities, but two straightforward, currently-bookable options anchor the budget end:"},
  {"t":"stays","items":[
    {"name":"Hostal Santa Ana","area":"Barri Gòtic","program":"booking","query":"Hostal Santa Ana Barcelona",
     "blurb":"Central and historic-core, a few streets from the cathedral. Booking-rated 7.6/10, good value, free WiFi — the reliable budget pick in the old town."},
    {"name":"Somnio Hostels","area":"Eixample","program":"booking","query":"Somnio Hostels Barcelona",
     "blurb":"Renovated in 2023, a short walk from Las Ramblas. Booking-rated 7.7/10 — the budget pick if you'd rather base in Eixample than the old town."},
  ]},
  {"t":"book","head":"Compare Barcelona hotels & hostels","html":"Booking.com has the deepest Barcelona inventory and free cancellation on most rooms — useful for weighing old-town against Eixample against beachside before you commit to anything.","program":"booking","query":"Barcelona","label":"See Barcelona stays on Booking"},
  {"t":"h2","text":"Mid-range: where most people should look"},
  {"t":"p","html":"This is Barcelona's sweet spot — design-forward hotels a short walk from the sights, roughly $150–190 a night."},
  {"t":"stays","items":[
    {"name":"Praktik Èssens","area":"Eixample · Passeig de Gràcia","band":"$188","program":"booking","query":"Praktik Essens Barcelona",
     "blurb":"A design-hotel feel right by Casa Batlló and La Pedrera. Rated 9.0/10 — the pick if you want to walk to the Gaudí landmarks."},
    {"name":"Acta Voraport","area":"Sant Martí · Poblenou","band":"$157","program":"booking","query":"Acta Voraport Barcelona",
     "blurb":"A 10-minute walk to Bogatell Beach, with a terrace and parking. Rated 9.0/10 — the pick if you want beach mornings over old-town lanes."},
  ]},
  {"t":"h2","text":"Boutique and splurge"},
  {"t":"p","html":"If the budget stretches further, two names worth it:"},
  {"t":"stays","items":[
    {"name":"Yurbban Passage Hotel & Spa","area":"Ciutat Vella","band":"$305","program":"booking","query":"Yurbban Passage Hotel Barcelona",
     "blurb":"An outdoor pool and spa tucked into the old-town center — genuinely rare at this location. Rated 9.1/10, our boutique pick."},
    {"name":"Mandarin Oriental Barcelona","area":"Eixample · Passeig de Gràcia","band":"$938","program":"booking","query":"Mandarin Oriental Barcelona",
     "blurb":"The flagship luxury address on Passeig de Gràcia, rated 9.1/10 — if the budget is genuinely open."},
  ]},
  {"t":"tip","head":"Hotel vs. short-term rental","html":"Short-term tourist apartments are currently the single most politically charged accommodation choice in Barcelona — the city has moved to phase out their licenses amid real housing pressure, and a 2017 survey found roughly 60% of residents felt the city had reached or exceeded what it could handle from tourism. Every hotel above is the lower-friction, more locally accepted option, and one more reason to book one of them instead of an apartment listing."},
  {"t":"h2","text":"When to book"},
  {"t":"ul","items":[
    "<strong>High season is June–August</strong>, when Barcelona is warmest and busiest — book four to six weeks ahead for anything in the Gòtic or Eixample.",
    "<strong>May–June and September–October are the sweet spot</strong> — warm, thinner crowds, easier availability and better prices than August.",
    "<strong>Gràcia's Festa Major</strong> (mid-August) turns the neighborhood into a giant street-decoration competition, block by block — wonderful if you catch it, but book a Gràcia stay for that week well ahead.",
    "<strong>August has a real trade-off:</strong> it's the easiest month to find a room, but also when a lot of the small, family-run places in our <a class='inline' href='/barcelona/where-to-eat-in-barcelona/'>food guide</a> close for a few weeks. You'll sleep easily — just double-check restaurant hours before building a day around one specific place.",
    "<strong>Winter is quietest and cheapest</strong>, with mild temperatures — a genuinely underrated time to visit if beach weather isn't the point.",
  ]},
  {"t":"book","head":"Ready to pick a place?","html":"Booking.com lets you filter by neighborhood and compare today's prices and cancellation terms side by side — the fastest way to weigh everything on this page against your dates.","program":"booking","query":"Barcelona","label":"See Barcelona hotels on Booking"},
 ],
 "faq":[
   ("Which area of Barcelona is best for a first-time visit?",
    "Barri Gòtic or El Born — both put you inside walking distance of the cathedral, the beach and most major sights, and both are as atmospheric at night as they're busy by day."),
   ("Is it better to stay near the beach or in the old town in Barcelona?",
    "Old town (Gòtic, Born, Raval) for walkability and history; Barceloneta or Poblenou for beach mornings and a quieter, more residential feel a few blocks off the sand. They're a short metro ride apart, so you're never far from either."),
   ("Should I book a hotel or a short-term rental apartment in Barcelona?",
    "A hotel. Short-term tourist apartments are currently the most politically sensitive accommodation choice in the city amid real housing pressure, and the city has moved to phase out their licenses — booking one of the hotels above is the lower-friction, more locally accepted option, at similar or better value."),
 ],
},

# ============================================================ THINGS TO DO
{
 "city":"barcelona", "slug":"best-things-to-do-in-barcelona", "order":3,
 "title":"Best Things to Do in Barcelona",
 "kicker":"Barcelona · Do",
 "dek":"The Gaudí sights worth booking weeks ahead, the free wandering that's just as good, and an honest note on visiting a city stretched thin by its own popularity.",
 "description":"What to do in Barcelona: the Gaudí sights worth booking ahead, the Gothic Quarter, Montjuïc, Montserrat day trips, and an honest overtourism note.",
 "read":"10 min", "updated":"July 2026",
 "related":["where-to-eat-in-barcelona","where-to-stay-in-barcelona","3-days-in-barcelona"],
 "blocks":[
  {"t":"lead","html":"You could fill two weeks here without repeating yourself. This is the honest shortlist — the sights that earn the hype, the ones you need to book before you land, and what's worth your time once you're past the postcard five."},
  {"t":"h2","text":"The Gaudí sights: book these first"},
  {"t":"p","html":"Antoni Gaudí's work is the reason most people come, and the two biggest sights now run timed, capped entry — buy ahead, or you may not get in at all."},
  {"t":"do","items":[
    {"name":"Sagrada Família","tag":"Book weeks ahead","blurb":"Gaudí's unfinished basilica is the single most-visited monument in Spain. Timed entry regularly sells out days ahead in high season — this is the one to sort before you land.","program":"gyg","query":"Sagrada Familia skip the line Barcelona","label":"See Sagrada Família tickets"},
    {"name":"Park Güell","tag":"Also book ahead","blurb":"Gaudí's mosaic park has capped entry to the monumental zone at roughly 800 visitors an hour since 2013. Same rule as the Sagrada Família: reserve a timed slot in advance.","program":"gyg","query":"Park Guell tickets Barcelona","label":"See Park Güell tickets"},
    {"name":"Casa Batlló","tag":"The dragon-roof one","blurb":"The more theatrical of Gaudí's two dueling Eixample apartment blocks on Passeig de Gràcia — a rippling, bone-like façade that looks like nothing else on the street.","program":"gyg","query":"Casa Batllo tickets Barcelona","label":"See Casa Batlló tickets"},
    {"name":"La Pedrera (Casa Milà)","tag":"The wavy stone one","blurb":"Gaudí's other Passeig de Gràcia masterpiece, a few doors from Casa Batlló — undulating stone, wrought-iron balconies, and a rooftop of surreal chimney sculptures.","program":"gyg","query":"La Pedrera Casa Mila tickets Barcelona","label":"See La Pedrera tickets"},
  ]},
  {"t":"book","head":"Book skip-the-line tickets before you land","html":"Sagrada Família and Park Güell aren't 'buy at the door' anymore — both routinely sell out days ahead in high season, and Casa Batlló isn't far behind. GetYourGuide is the easiest way to lock in timed slots for any of these in one place.","program":"gyg","query":"Gaudi Barcelona tickets","label":"Book Gaudí tickets"},
  {"t":"h2","text":"The Gothic Quarter, on foot"},
  {"t":"p","html":"Barri Gòtic is Barcelona's medieval core, built on the old Roman grid — the cathedral, Plaça Sant Jaume, Plaça Reial, and lanes that tangle enough to get pleasantly lost in. It's genuinely touristy by midday and genuinely atmospheric early morning or after dinner, once the day-trip crowds thin out."},
  {"t":"do","items":[
    {"name":"Wander it yourself","tag":"Free, self-guided","blurb":"No booking needed — start at the cathedral and let the lanes take you. Before 9am or after dinner is when it actually feels medieval rather than like a queue.","program":None},
    {"name":"A guided walking tour","tag":"If you want the history","blurb":"A couple of hours with a guide unlocks the Roman walls and the stories behind the squares that are easy to walk straight past otherwise.","program":"gyg","query":"Gothic Quarter walking tour Barcelona","label":"Find a walking tour"},
  ]},
  {"t":"h2","text":"Montjuïc: views, art and the fountain"},
  {"t":"p","html":"The hill above the port packs in a castle, one of Spain's best modern-art museums, and — some evenings — a genuinely spectacular free water-and-light show."},
  {"t":"do","items":[
    {"name":"Montjuïc Castle & cable car","tag":"Views","blurb":"A hilltop fortress with the best panoramic view of the port and the city, reachable by cable car for the ride itself as much as the destination.","program":"gyg","query":"Montjuic cable car Barcelona","label":"See Montjuïc tours"},
    {"name":"Joan Miró Foundation","tag":"Art","blurb":"One of Spain's best modern-art museums, dedicated to the Barcelona-born surrealist — a good indoor option when the sightseeing pace needs a break.","program":None},
    {"name":"Magic Fountain (Font Màgica)","tag":"Free, evenings","blurb":"A free sound-light-and-water show at the foot of Montjuïc on select evenings. Check the current schedule locally, but it's one of the best free things to do in the city.","program":None},
  ]},
  {"t":"h2","text":"La Boqueria — go early"},
  {"t":"p","html":"Barcelona's most famous market, just off La Rambla, is genuinely worth seeing — the trick is timing. Go early morning, before the tour groups arrive, and it's still a working market: fishmongers, fruit stalls, a jamón counter slicing to order. By midday it's mostly a photo line. For markets locals actually shop at, <a class='inline' href='/barcelona/where-to-eat-in-barcelona/'>our food guide</a> points to Mercat de Sant Antoni and Mercat de la Barceloneta instead."},
  {"t":"warn","head":"Camp Nou: check before you plan around it","html":"FC Barcelona's stadium has been mid-renovation since June 2023, targeting completion around June 2026. The club returned to partial operation in November 2025 at reduced capacity, expanding toward roughly 62,700 seats by March 2026 — and the stadium tour and museum, which normally draw more than 1.2 million visitors a year, are genuinely in flux this season. If a Camp Nou visit matters to your trip, verify the current tour format and availability close to your dates rather than assuming it's business as usual."},
  {"t":"h2","text":"Day trips: Montserrat and the Costa Brava"},
  {"t":"p","html":"The best reason to leave the city for a day."},
  {"t":"do","items":[
    {"name":"Montserrat","tag":"The classic day trip","blurb":"A jagged mountain monastery about an hour out by train plus rack railway or cable car — home to the Black Madonna ('La Moreneta') and a centuries-old boys' choir, with the summit of Sant Jeroni at 1,236m for anyone who wants to hike beyond the monastery itself.","program":"gyg","query":"Montserrat day trip Barcelona","label":"See Montserrat day trips"},
    {"name":"Costa Brava","tag":"Coast & medieval towns","blurb":"Coastal towns a couple of hours northeast — cobbled Girona and the walled beach town of Tossa de Mar are the two names that come up most.","program":"gyg","query":"Costa Brava day trip Barcelona","label":"See Costa Brava day trips"},
  ]},
  {"t":"h2","text":"Beach, sailing and a night out"},
  {"t":"p","html":"Barceloneta beach is the closest sand to the center — a former fishermen's quarter turned boardwalk, livelier right on the sand and calmer a few blocks inland."},
  {"t":"do","items":[
    {"name":"Barceloneta beach","tag":"Closest beach","blurb":"The city's most convenient beach and boardwalk, with seafood chiringuitos along the front. Go a few blocks inland for a quieter, more residential version of the same neighborhood.","program":None},
    {"name":"Sunset sailing or catamaran","tag":"Pairs well with the beach","blurb":"A couple of hours on the water off Barceloneta is a genuinely nice way to see the skyline from the sea, especially around sunset.","program":"gyg","query":"sunset catamaran cruise Barcelona","label":"See sailing tours"},
    {"name":"Tapas & vermút crawl","tag":"Already in our food guide","blurb":"A guided tasting crawl through the Born and the Gòtic is covered in full in <a class='inline' href='/barcelona/where-to-eat-in-barcelona/'>our food guide</a> — the better move on a first trip, when you don't yet know which bar does what.","program":None},
    {"name":"Flamenco show","tag":"Andalusian, not Catalan","blurb":"Worth knowing before you go: flamenco is originally Andalusian, not a Catalan tradition. Barcelona still has established tourist-facing tablaos, among them Tablao Cotton Club and Palau Dalmases, plus shows at Poble Espanyol.","program":"gyg","query":"flamenco show Barcelona","label":"See flamenco shows"},
  ]},
  {"t":"callout","head":"An honest note on overtourism","html":"Barcelona is one of Europe's most visible overtourism flashpoints, and it's a live issue, not settled history. The city was already logging more than 9 million annual visitors by 2013; by 2017, surveys found roughly 60% of residents felt the city had reached or exceeded what it could handle. Housing pressure from short-term rentals has been severe enough that the city has moved to phase out short-term tourist-apartment licenses, and Park Güell's visitor cap and active limits on cruise-ship arrivals are part of the same response. None of that means don't come — it means come a little differently: book the timed tickets above so you're not part of an unmanaged crush, treat the residential streets around Park Güell and the Gòtic's courtyards as someone's home rather than a backdrop, spread your sightseeing across a few unhurried days instead of a checklist-sprint, and eat somewhere from <a class='inline' href='/barcelona/where-to-eat-in-barcelona/'>our food guide</a> that isn't on the Rambla. It's a better trip anyway."},
 ],
 "faq":[
   ("Do I need to book Sagrada Família and Park Güell tickets in advance?",
    "Yes — both routinely sell out days ahead in high season and now run timed, capped entry rather than walk-up access. Book through GetYourGuide before you land, especially for a summer trip."),
   ("Is Camp Nou open to visitors right now?",
    "Partially. The stadium has been under major renovation since June 2023 and returned to partial operation at reduced capacity in November 2025. Check the current tour format and availability close to your travel dates rather than assuming normal access."),
   ("Is Barcelona too crowded to visit right now?",
    "The hotspots — La Rambla, the Sagrada Família queue, Park Güell at midday — are genuinely strained, but the city is much bigger than its five famous sights. Visiting in May–June or September–October, booking tickets ahead, and spending time in neighborhoods like Gràcia or Sant Andreu goes a long way toward a better trip, for you and the city both."),
 ],
},

# ============================================================ 3-DAY ITINERARY
{
 "city":"barcelona", "slug":"3-days-in-barcelona", "order":4,
 "title":"3 Days in Barcelona: The Perfect Itinerary",
 "kicker":"Barcelona · Itinerary",
 "dek":"Old town on Day 1, Gaudí start to finish on Day 2, and a Day 3 that flexes to views, beach or a mountain monastery — with what to book before you land.",
 "description":"A 3-day Barcelona itinerary: Gothic Quarter and El Born, a full Gaudí day, then Montjuïc, the beach or Montserrat — with what to book ahead.",
 "read":"9 min", "updated":"July 2026",
 "related":["where-to-eat-in-barcelona","where-to-stay-in-barcelona","best-things-to-do-in-barcelona"],
 "blocks":[
  {"t":"lead","html":"Three days is enough to do Barcelona properly, as long as you don't try to see everything. This plan follows the way the city actually sits on the map — one day in the old town, one day following Gaudí across the Eixample, and a third that flexes to whatever kind of trip you're on."},
  {"t":"h2","text":"The plan at a glance"},
  {"t":"compare","head":["Day","Focus","Neighborhoods"],
   "rows":[
     ["<strong>Day 1</strong>","Old town: medieval lanes, a market, a 200-year-old bar","Barri Gòtic, El Born, El Raval"],
     ["<strong>Day 2</strong>","Gaudí, start to finish","Sagrada Família, Eixample, Park Güell, Gràcia"],
     ["<strong>Day 3</strong>","Your choice: views, beach or a mountain","Montjuïc, Barceloneta, or Montserrat"],
   ],
   "cap":"Swap the order if it suits your hotel's location better — nothing here needs to happen in this exact sequence except the ticket-booking below."},
  {"t":"book","head":"Book these two before anything else","html":"Sagrada Família and Park Güell run timed, capped entry and routinely sell out days ahead in high season. Lock in both before you plan anything else about this trip.","program":"gyg","query":"Sagrada Familia and Park Guell tickets Barcelona","label":"Book Sagrada Família & Park Güell"},
  {"t":"h2","text":"Day 1: Gothic Quarter, El Born & La Boqueria"},
  {"t":"p","html":"Start in the <strong>Barri Gòtic</strong> early, before the day-trip crowds fill it in — the medieval core, built on the old Roman grid. The cathedral, Plaça Sant Jaume and Plaça Reial are all walkable from each other, and the tangled lanes between them are the point: put the map away for twenty minutes."},
  {"t":"p","html":"By late morning, walk to <strong>La Boqueria</strong> off La Rambla while it's still a working market rather than a photo line — fishmongers, fruit stalls, a jamón counter. Eat lunch at a counter inside rather than a sit-down table on the Rambla itself."},
  {"t":"p","html":"Spend the afternoon in <strong>El Born</strong>: the Picasso Museum and the Santa Maria del Mar basilica, then get pleasantly lost in the boutique streets around Passeig del Born. It's more polished than the Gòtic next door, and a good slower gear after a market morning."},
  {"t":"p","html":"For the evening, either stay in El Born or cross into El Raval for one specific stop worth the detour:"},
  {"t":"eats","items":[
    {"name":"Bodega del Born","slug":"bodega-del-born","area":"El Born","blurb":"A brick-walled wine bar a few streets from where you'll have spent the afternoon — anchovies with strawberry jam, and a vermouth flight served 'in order of complexity.'"},
    {"name":"Bar Marsella","slug":"bar-marsella","area":"El Raval","blurb":"Barcelona's most storied bar, pouring drinks since 1820 — order the house absinthe and sit with it. Fifteen minutes' walk from El Born, and worth the detour on your first night."},
  ]},
  {"t":"p","html":"The full ranked list of where to eat and drink is in <a class='inline' href='/barcelona/where-to-eat-in-barcelona/'>our food guide</a> — this is just the pair that fits a Day 1 evening best."},
  {"t":"h2","text":"Day 2: Gaudí, start to finish"},
  {"t":"p","html":"<strong>Sagrada Família</strong> first thing, with your timed slot already booked. Give it a genuine hour or more — it rewards slowing down more than almost any sight in the city."},
  {"t":"p","html":"Walk or take the metro to <strong>Passeig de Gràcia</strong> for Gaudí's two dueling apartment blocks, <strong>Casa Batlló</strong> and <strong>La Pedrera</strong> — a few doors apart, both worth seeing from outside even if you only go in one. This stretch of Eixample is also the city's smartest shopping."},
  {"t":"p","html":"<strong>Park Güell</strong> in the afternoon, on your other pre-booked timed slot — the monumental zone is capped at roughly 800 visitors an hour, so this isn't one to wing on arrival."},
  {"t":"p","html":"Park Güell sits at the edge of <strong>Gràcia</strong>, the least touristy of the central neighborhoods and an easy walk down from the park — a former village annexed into the city in 1897 that still feels like one. Have dinner here rather than trekking back to the old town."},
  {"t":"eats","items":[
    {"name":"Bodega Marín","slug":"bodega-marin","area":"Gràcia","blurb":"Owner-run, fast and unpretentious — genuinely comfortable to eat solo at the bar if you've spent the day on your feet alone."},
    {"name":"Vermuteria Puigmartí","slug":"vermuteria-puigmarti","area":"Gràcia","blurb":"Home of 'patates Puigmartí' and about as unbothered by tourism as this city gets."},
    {"name":"Xocolateria La Nena","slug":"xocolateria-la-nena","area":"Gràcia","blurb":"Thick hot chocolate and churros, if you'd rather end the day sweet than savory."},
  ]},
  {"t":"h2","text":"Day 3: pick your ending"},
  {"t":"p","html":"Three honest options, depending on what kind of trip this is. Pick one — or, with a fourth day, do two."},
  {"t":"h3","text":"Option A: Montjuïc"},
  {"t":"p","html":"The hilltop park and fortress above the port — Montjuïc Castle and a cable car for the view, the Joan Miró Foundation if you want one more museum, and the free Magic Fountain show if the evening schedule lines up. The whole hill is a half-to-full day depending on your pace."},
  {"t":"h3","text":"Option B: Barceloneta beach"},
  {"t":"p","html":"If three days of walking has you wanting to sit still, Barceloneta is the closest sand to the center — boardwalk, seafood chiringuitos, and a former fishermen's quarter a few blocks inland that's calmer than the beachfront itself."},
  {"t":"eats","items":[
    {"name":"La Taberna de la Barceloneta","slug":"la-taberna-de-la-barceloneta","area":"Barceloneta","blurb":"Octopus 'bomba' and a paella that actually earns its socarrat crust, a few streets from the sand."},
  ]},
  {"t":"h3","text":"Option C: Montserrat day trip"},
  {"t":"p","html":"If you'd rather leave the city entirely, Montserrat is the move — a jagged mountain monastery about an hour out by train plus rack railway or cable car, home to the Black Madonna and a centuries-old boys' choir. It's a full day, so it only fits if you're willing to trade the beach or Montjuïc for it."},
  {"t":"book","head":"Book Montserrat ahead if you're doing Option C","html":"The train-plus-cable-car combination is easiest to arrange as a single ticket rather than piecing it together on the day itself.","program":"gyg","query":"Montserrat day trip Barcelona","label":"See Montserrat day trips"},
  {"t":"tip","head":"Getting between all of this","html":"Buy a T-casual card at any metro machine — 10 journeys, shareable between however many of you are traveling, and zone 1 covers every stop in this plan. The old-town core (Gòtic, Born, Raval, Eixample-Dreta) is flat and walkable on its own; save the metro for the longer hops to Park Güell, Gràcia or Montjuïc."},
  {"t":"callout","head":"Traveling this itinerary considerately","html":"Barcelona is genuinely strained by how many people want to see it. Treat the residential streets around Park Güell and the Gòtic's courtyards as someone's home, not a backdrop — this plan already leans that way: Gràcia over the Rambla for dinner, a hotel over a short-term rental (see our <a class='inline' href='/barcelona/where-to-stay-in-barcelona/'>stays guide</a>), neighborhood bars over tourist-menu restaurants. More on this in <a class='inline' href='/barcelona/best-things-to-do-in-barcelona/'>our full do guide</a>."},
  {"t":"h2","text":"If you have more time"},
  {"t":"p","html":"Five to seven days lets you slow down: add a beach day without rushing it, go further into Sant Andreu or Horta-Guinardó for a meal (both in <a class='inline' href='/barcelona/where-to-eat-in-barcelona/'>our food guide</a>), or use Barcelona as a base for the Costa Brava instead of just Montserrat. Everything in this three-day plan still holds — you're just not compressing it."},
  {"t":"btnrow","btns":[
    {"program":"airalo","query":"spain","label":"Get a Spain eSIM (Airalo)"},
    {"program":"safetywing","label":"Travel insurance (SafetyWing)","style":"btn-forest"},
  ]},
 ],
 "faq":[
   ("Is 3 days enough for Barcelona?",
    "Yes, for the essentials — the Gaudí landmarks, the old town, and a proper meal in a couple of neighborhoods. Five to seven days is better if you want to add Montserrat or the Costa Brava, a real beach day, or just stop rushing between sights."),
   ("Do I need to book Sagrada Família and Park Güell before this trip?",
    "Yes — both run timed, capped entry and routinely sell out days ahead in high season. Book both before you sort anything else in this itinerary."),
   ("What's the best way to get around Barcelona in 3 days?",
    "Mostly on foot — the old town and Eixample-Dreta are flat and walkable. A T-casual card (10 metro/bus journeys, shareable) covers the longer hops out to Park Güell, Gràcia or Montjuïc."),
 ],
},

]
