# -*- coding: utf-8 -*-
# BEIRUT — food-forward city hub + one deep guide.
# All specifics sourced from our own vetted business dataset + light web research (July 2026).
# Sensitive-destination tone: warm celebration of food/neighborhoods, one honest advisory note,
# hotel CTAs kept light. No place, price or rating here is invented — see research/city-beirut.md.

CITY = {
 "id": "beirut",
 "intro_blocks": [
  {"t":"lead","html":"Beirut eats before it does almost anything else. This is a city where a hundred-year-old falafel counter and a two-seating chef's table sit four kilometers apart, where breakfast is a genuine destination, and where the table is still — whatever else is happening around it — the center of everything. Here's how to eat and move through it well."},
  {"t":"p","html":"Lebanese food doesn't really have a 'scene' so much as a rhythm: foul and hummus at dawn, manoushe mid-morning, mezze stretching across a whole evening, sweets whenever. Beirut does all of it, spread across neighborhoods with sharply different personalities. <strong>Hamra</strong>, Ras Beirut's bustling commercial spine around the American University of Beirut, is dense with breakfast counters and bookshop cafés and rarely quiet. <strong>Mar Mikhael</strong>, down by the water, turns into Beirut's liveliest bar strip after dark, its restaurants and grills feeding the same crowd. <strong>Gemmayzeh</strong>, one flight of stairs away — literally, the Saint Nicolas Stairs connect them — fills French-mandate-era buildings with bars, street art and a slightly calmer version of the same energy. Up the hill, <strong>Achrafieh</strong> is Beirut's elegant, red-roofed quarter, home to sweets shops and quieter, more refined tables. And across town, <strong>Bourj Hammoud</strong> — settled by Armenian refugees in the early twentieth century and still the heart of Armenian Beirut — has an entirely distinct food identity: basterma, soujouk, kebbe, a whole cured-meat and mezze culture you won't find in the same form anywhere else in the city."},
  {"t":"h2","text":"Where to eat first"},
  {"t":"p","html":"Start with these eight. The full ranked list of fifteen — plus the specific dishes to order — is in our <a class='inline' href='/beirut/where-to-eat-in-beirut/'>Beirut food guide</a>."},
  {"t":"eats","ranked":True,"items":[
    {"name":"LMATBAKH","slug":"lmatbakh","area":"Mar Mikhael",
     "blurb":"The city's most talked-about modern table: a live chef's-counter tasting menu cooked in front of you over two nightly seatings only. Dine-in, reservations essential."},
    {"name":"Abou Abdallah","slug":"abou-abdallah","area":"Dawra",
     "blurb":"A Dawra breakfast temple that's served foul and fetteh since 6am under old-Lebanon décor with Fairuz playing low — the kind of place locals treat like a secret."},
    {"name":"Abu Hassan Hummus & Fool","slug":"abu-hassan","area":"Hamra",
     "blurb":"Hamra's 24-hour hummus institution — fattet laban, falafel and fries at any hour, in the huge portions this family-run kitchen is known for."},
    {"name":"Malek al Foul","slug":"malek-al-foul","area":"Hamra",
     "blurb":"Hand-mashed hummus and foul unchanged since 1965, at a small counter near AUB that three generations of students have called breakfast."},
    {"name":"Falafel Tabbara","slug":"falafel-tabbara","area":"Mar Elias",
     "blurb":"Falafel fried to order by a hajj who's worked the same counter for 60-plus years, in a shop that's been open for more than a century."},
    {"name":"Basterma Mano","slug":"basterma-mano","area":"Bourj Hammoud",
     "blurb":"Cured meats and shawarma since 1966 — the single most-reviewed business in this whole city, and the fastest way to understand Bourj Hammoud's Armenian food culture."},
    {"name":"Kahwet 60","slug":"kahwet-60","area":"Gemmayze",
     "blurb":"A big Lebanese breakfast spread on a 60s/70s-retro rooftop with skyline views over Gemmayze, plus a serious shisha game."},
    {"name":"Le Flocon Artisan Glacier","slug":"le-flocon","area":"Achrafieh",
     "blurb":"The prettiest ice-cream counter in the city — salted-caramel booza sculpted into fruit shapes, including a strawberry that actually looks like one."},
  ]},
  {"t":"h2","text":"Where to stay"},
  {"t":"p","html":"Beirut's hotel scene took a hit after 2020 and is still rebuilding, but a handful of properties are reliable, well-run and currently bookable — worth reconfirming close to your dates, as with most things here."},
  {"t":"stays","items":[
    {"name":"Queens Suite Hotel","area":"Hamra","band":"$70–90","program":"booking","query":"Queens Suite Hotel Beirut",
     "blurb":"Small serviced suites right in Hamra's restaurant strip — a step up from a hostel without boutique pricing, and walking distance to half the eats above."},
    {"name":"The Smallville Hotel","area":"Badaro","band":"$200","program":"booking","query":"The Smallville Hotel Beirut",
     "blurb":"A design-forward hotel in a converted residential building with a rooftop pool and bar — steps from the National Museum and Badaro's café strip."},
    {"name":"Hotel Albergo","area":"Achrafieh","band":"£380","program":"booking","query":"Hotel Albergo Beirut",
     "blurb":"A converted Ottoman-era mansion and Relais & Châteaux member with a rooftop terrace over the city — one of Beirut's longest-running, best-known boutique stays."},
    {"name":"InterContinental Phoenicia Beirut","area":"Downtown","band":"£220","program":"booking","query":"InterContinental Phoenicia Beirut",
     "blurb":"The grand seafront hotel of Beirut's golden age, now IHG-run — the easiest big-name splurge if you want a known quantity on a first trip."},
  ]},
  {"t":"book","head":"Comparing dates?","html":"Booking.com has the widest live Beirut inventory across all four of these, plus everything in between.","program":"booking","query":"Beirut","label":"See Beirut stays on Booking"},
  {"t":"h2","text":"What to see"},
  {"t":"do","items":[
    {"name":"Corniche & Pigeon Rocks","tag":"Free, self-guided",
     "blurb":"A 4.8km seafront promenade for walking, jogging or watching the sunset — follow it out to Raouché for a free view of the Pigeon Rocks, Beirut's only natural sea arches."},
    {"name":"Beirut National Museum","tag":"Badaro",
     "blurb":"About 1,300 Phoenician-to-Mamluk artifacts, including the Byblos figurines — plus the quietly remarkable story of how staff protected the collection through the civil war."},
    {"name":"Sursock Museum","tag":"Achrafieh",
     "blurb":"Modern and contemporary art across 800-plus works in a grand Achrafieh building, with the still-private Sursock Palace visible right across the street."},
    {"name":"Beirut Souks & Downtown","tag":"Martyrs' Square",
     "blurb":"The rebuilt heart of the city — 200-plus shops in a polished, walkable streetscape, and a good bookend to a Downtown afternoon."},
    {"name":"Jeita Grotto, Byblos & Harissa","tag":"Day trip","program":"gyg","query":"Jeita Grotto Byblos Harissa day trip","label":"See day trip options",
     "blurb":"The single most popular day out of Beirut: a vast cave system, the Crusader-era harbor town of Byblos, and a cable car up to the Harissa statue."},
    {"name":"Bourj Hammoud food walk","tag":"Self-guided",
     "blurb":"Wander the Armenian quarter's dense market streets past basterma and soujouk shops and Armenian churches — pairs perfectly with lunch at Basterma Mano or Resto Ghazar."},
  ]},
  {"t":"h2","text":"Getting there & around"},
  {"t":"p","html":"Beirut–Rafic Hariri International (BEY) is Lebanon's only airport, about 15–25 minutes from Hamra, Downtown or Achrafieh depending on traffic. The official taxi counters inside arrivals are the simplest first move — agree the fare before you get in. Bolt also operates across the city with metered, no-haggling fares, though it can be hit-or-miss picking up right at the airport."},
  {"t":"ul","items":[
    "<strong>Around town:</strong> each neighborhood is walkable in itself, but sidewalks between them are patchy, so a short Bolt or taxi hop — Hamra to Mar Mikhael, say — is normal and cheap. Don't assume you can just walk it.",
    "<strong>Cash rules here.</strong> Beirut has run on a cash-and-USD basis since the 2019–2020 banking crisis. Bring more small, crisp US bills than you think you'll need — card acceptance is inconsistent outside upscale places, and ATMs can be unreliable.",
    "<strong>Power cuts are normal.</strong> Grid electricity is widely supplemented by neighborhood generator subscriptions; hotels and restaurants handle it seamlessly and it isn't something to worry about.",
  ]},
  {"t":"warn","head":"Before you go","html":"Lebanon currently carries formal government travel advisories, and they're worth taking seriously — but they aren't uniform. Several governments currently draw a real distinction between Beirut and Mount Lebanon, generally urging caution there, and the south and border areas, which carry stronger warnings; a cessation of hostilities announced in spring 2026 has held, though both the US and UK describe the situation as fluid. Advisories are updated often and differ by country, so treat this paragraph as a starting point, not the final word. Check your own government's current, dated advisory — <strong>travel.state.gov</strong> for US citizens, <strong>gov.uk/foreign-travel-advice</strong> for UK citizens — before you book, and again closer to your trip, and consider registering with your embassy once you're there."},
  {"t":"tip","head":"Best time to visit","html":"<strong>April–June and September–October</strong> are the sweet spot — warm, dry and comfortable, good for both the coast and day trips. <strong>July–August</strong> is hot and the busiest, priciest season, as the diaspora comes home for summer. <strong>Winter</strong> is mild by regional standards, with occasional storms, and the cheapest hotel rates alongside November and March. Lebanon is often called the only country in the Levant with genuine four-season variation — a mild coast within an hour of snow in the mountains."},
 ],
 "faq": [
  ("Is it safe to travel to Beirut right now?",
   "It depends on your own government's current advisory, which is exactly why we won't give you a flat yes or no here. Several governments currently distinguish between Beirut and Mount Lebanon — generally urging caution rather than an outright ban — and the country's south and border areas, which carry stronger warnings. Check the current, dated advisory at travel.state.gov or gov.uk/foreign-travel-advice before you book, and again closer to your trip."),
  ("How many days do you need in Beirut?",
   "Three or four days is enough to work through several neighborhoods and eat very well. Add a day if you want the Jeita Grotto–Byblos–Harissa day trip, the single most popular excursion out of the city."),
  ("What should I eat first in Beirut?",
   "Start where Beirut itself starts: a foul-and-hummus breakfast at a counter like Abou Abdallah or Malek al Foul, then a manoushe an hour later because you'll want one. Our full <a class='inline' href='/beirut/where-to-eat-in-beirut/'>food guide</a> has the rest, ranked."),
 ],
}

PAGES = [

# ============================================================ WHERE TO EAT
{
 "city":"beirut", "slug":"where-to-eat-in-beirut", "order":1,
 "title":"Where to Eat in Beirut: A Local Food Guide",
 "kicker":"Beirut · Food",
 "dek":"Fifteen places worth crossing the city for, the Lebanese dishes you have to order, and which neighborhood to eat in — from a hummus counter unchanged since 1965 to a two-seating chef's table.",
 "description":"The real Beirut food guide: 15 ranked local eats, the Lebanese dishes to order, and which neighborhood to eat in — from century-old counters to a chef's table.",
 "read":"12 min", "updated":"July 2026",
 "related":[],
 "blocks":[
  {"t":"lead","html":"Beirut eats before it does almost anything else. This is a city where a hundred-year-old falafel counter and a two-seating chef's table sit four kilometers apart, where breakfast is a genuine destination, and where the table is still — whatever else is happening around it — the center of everything. Here's where to go, ranked."},
  {"t":"h2","text":"15 places worth crossing the city for"},
  {"t":"p","html":"This list runs from a 1965 hummus counter to a modern chef's table, chosen for being genuinely excellent and genuinely Beiruti — not for being easy to find. All fifteen have real menus, real regulars and real reviews behind them."},
  {"t":"eats","ranked":True,"items":[
    {"name":"LMATBAKH","slug":"lmatbakh","area":"Mar Mikhael",
     "blurb":"Chefs Christine Saad and Elie Harb cook a modern Lebanese tasting menu live at the counter in front of you, over two nightly seatings only. Dine-in only, and you'll want to book ahead — this is Beirut's most talked-about table right now."},
    {"name":"Abou Abdallah","slug":"abou-abdallah","area":"Dawra",
     "blurb":"Doors open at 6am for foul and fetteh under old-Lebanon décor with Fairuz on low — a Dawra institution that feels like a secret even though every local already knows it."},
    {"name":"Abu Hassan Hummus & Fool","slug":"abu-hassan","area":"Hamra",
     "blurb":"Open 24 hours, every day. Fattet laban, falafel and fries any time you need them, in portions the family running it clearly isn't trying to skimp on."},
    {"name":"Malek al Foul","slug":"malek-al-foul","area":"Hamra",
     "blurb":"'The King of Foul' — hand-mashed hummus and foul served exactly the way it has been since 1965, at a small counter that's fed three generations of AUB students."},
    {"name":"Abu Shadi Lebanese Pizza Manousheh","slug":"abu-shadi","area":"Hamra",
     "blurb":"No sign on the street, and by local accounts the best manakeesh in Hamra — go for the sabanekh (spinach) and cheese."},
    {"name":"Falafel Tabbara","slug":"falafel-tabbara","area":"Mar Elias",
     "blurb":"A hajj has fried falafel to order at this same counter for 60-plus years, in a shop that's been open more than a century. Generous, clean, busy at any hour."},
    {"name":"Falafel Abou Nabil & Sons","slug":"falafel-abou-nabil",
     "blurb":"Reviewers routinely call this the best falafel sandwich in the city — a crisp wrap with chili pickles from a proper family-run 'and Sons' operation."},
    {"name":"Al Daouk Sweets","slug":"al-daouk","area":"Tareek Jdeede",
     "blurb":"Home of the Daoukieh: pistachio, ashta and syrup layered the way this shop invented it back in 1961. Seven branches now, all doing the same thing well."},
    {"name":"Hamdi Al Zahabi Sweets","slug":"hamdi-al-zahabi","area":"Barbour",
     "blurb":"An old-school Barbour sweets counter — knafeh, baklava, halawet el jibn and maamoul b ashta straight off the tray, with generous staff and fair prices."},
    {"name":"Basterma Mano","slug":"basterma-mano","area":"Bourj Hammoud",
     "blurb":"Basterma, soujouk and shawarma since 1966 — and, with over 4,000 reviews, the single most-reviewed business in this whole guide. A Bourj Hammoud legend, not an exaggeration."},
    {"name":"Resto Ghazar","slug":"resto-ghazar","area":"Bourj Hammoud",
     "blurb":"Bold, authentic Armenian home cooking — mhammara and kebbe with cheese and soujouk — on Bourj Hammoud's liveliest strip."},
    {"name":"Kahwet 60","slug":"kahwet-60","area":"Gemmayze",
     "blurb":"A big Lebanese breakfast spread on a 60s/70s-retro rooftop with skyline views over Gemmayze, plus a serious shisha game and good desserts."},
    {"name":"Taht El Shajra","slug":"taht-el-shajra","area":"Hamra",
     "blurb":"'Under the Tree' — rich Arabic coffee and inventive plates like halloum with figs and walnuts, in a lovingly decorated Hamra hideout that runs breakfast through dinner."},
    {"name":"Le Flocon Artisan Glacier","slug":"le-flocon","area":"Achrafieh",
     "blurb":"Salted-caramel booza sculpted into fruit shapes — including a strawberry ice cream shaped like an actual strawberry. The prettiest ice-cream counter in Achrafieh."},
    {"name":"Zmrd Social Space","slug":"zmrd-social-space","area":"Furn El-Chebbak",
     "blurb":"Tea poured from a pot, apricot crumble, walnut cake, and owners who'll sit and talk with you — the coziest corner in Furn El-Chebbak. Closed Sundays."},
  ]},
  {"t":"h2","text":"Six dishes to build a trip around"},
  {"t":"do","items":[
    {"name":"Manoushe","tag":"Breakfast flatbread",
     "blurb":"Za'atar, cheese or spiced meat baked fresh on a stone oven — the definitive Lebanese breakfast. Abu Shadi's spinach-and-cheese version, behind an unmarked Hamra storefront, is one of the best."},
    {"name":"Foul & hummus","tag":"The morning ritual",
     "blurb":"Fava beans and chickpeas, olive oil, and a genuine daily habit rather than a tourist dish. Abou Abdallah, Abu Hassan and Malek al Foul are three completely different doors into the same tradition."},
    {"name":"Mezze spread","tag":"Any evening",
     "blurb":"Hummus, moutabal, tabbouleh, fattoush, kibbeh, stuffed vine leaves — shared, family-style, across the whole table. Order too much on purpose."},
    {"name":"Knefeh","tag":"Sweet, warm, syrup-soaked",
     "blurb":"Semolina-and-cheese pastry soaked in syrup, eaten as a sweet breakfast or dessert. Hamdi Al Zahabi Sweets serves it fresh off the tray alongside baklava and halawet el jibn."},
    {"name":"Lebanese wine","tag":"Bekaa Valley",
     "blurb":"The Bekaa Valley is one of the world's oldest wine regions — look for bottles from Château Ksara, Château Kefraya, Massaya, Domaine des Tourelles or IXSIR on a Beirut wine list."},
    {"name":"Armenian Bourj Hammoud","tag":"A different Beirut entirely",
     "blurb":"Basterma, soujouk, mante, kebbe — Bourj Hammoud's Armenian cooking is its own culinary layer. Beyond Basterma Mano and Resto Ghazar above, look for <strong>Apo</strong> (Armenian BBQ since 1976), <strong>Restaurant Varouj</strong> (45-plus years, no menu — you eat what Varouj cooks) and <strong>Falafel Arax</strong> (Armenian falafel since 1949)."},
  ]},
  {"t":"h2","text":"Where to eat, by neighborhood"},
  {"t":"p","html":"Beirut's food doesn't cluster by cuisine so much as by neighborhood mood — here's the shorthand, cross-referenced with the list above."},
  {"t":"compare","head":["Neighborhood","Feel","Eat here for"],
   "rows":[
     ["<strong>Hamra</strong>","AUB's dense, bustling commercial spine — busy at almost any hour","Breakfast institutions, hummus and foul, manoushe, falafel"],
     ["<strong>Mar Mikhael</strong>","Seaside, and Beirut's liveliest bar strip after dark","Modern Lebanese chef's tables and grills"],
     ["<strong>Gemmayzeh</strong>","French-mandate townhouses and street art, a stair-climb from Mar Mikhael","Retro-rooftop breakfast, old-school chicken, seafood"],
     ["<strong>Achrafieh</strong>","Beirut's elegant, red-roofed hillside quarter","Artisan ice cream, sweets, refined sit-down Lebanese"],
     ["<strong>Bourj Hammoud</strong>","The Armenian quarter — dense market streets and churches","Basterma, soujouk, kebbe, Armenian home cooking"],
     ["<strong>Badaro</strong>","Tree-lined and increasingly hip, next to the National Museum","Café culture, and a couple of genuinely different modern spots"],
   ],
   "cap":"Most of these sit a short, cheap Bolt ride apart — a Hamra breakfast and a Mar Mikhael dinner in the same day is completely normal here."},
  {"t":"book","head":"Want it guided?","html":"A 3–4 hour street-food walking tour through manakish bakeries, foul counters and dessert shops is a genuinely good way to get oriented on day one, especially if this list feels like a lot to plan yourself.","program":"gyg","query":"Beirut food tour","label":"Find a Beirut food tour"},
  {"t":"tip","head":"Eating out, practically","html":"Most of the places on this list are cash-only, family-run counters — bring small US bills, since card acceptance is inconsistent outside the fancier spots. A few keep unusual hours worth planning around: Abu Hassan never closes, Abou Abdallah opens at 6am, and Zmrd Social Space is closed on Sundays. Come hungry, and don't rush the table — that's rather the whole point."},
 ],
 "faq":[
   ("What's the best neighborhood to eat in Beirut?",
    "There isn't one — that's the fun of it. Hamra has the breakfast institutions and hummus counters, Mar Mikhael and Gemmayzeh have the modern kitchens and grills, Achrafieh has the sweets, and Bourj Hammoud has an entire Armenian food culture you won't find anywhere else in the city. Plan to hit at least three."),
   ("Is street food safe to eat in Beirut?",
    "Generally yes, by the usual rule: go where the queue and the turnover are both high. Places like Abu Hassan and Falafel Tabbara have been run by the same families for decades and are trusted by locals every single day — that track record, plus food made fresh in front of you, is the best signal you'll get."),
   ("Do I need cash to eat out in Beirut?",
    "Mostly, yes. Most of the counters and family-run spots on this list are cash-only, and Beirut has operated on a cash-and-US-dollar basis since the 2019–2020 banking crisis. Bring small, crisp USD bills — card acceptance is inconsistent outside the more upscale restaurants."),
 ],
},

]
