# -*- coding: utf-8 -*-
# BERLIN — depth pack: stays, essential sights, and a 3-day itinerary.
# Facts sourced from research/city-berlin.md + well-known Berlin general
# knowledge (July 2026). No CITY block here — berlin.py owns that; this
# file only adds three more articles to the same city.

PAGES = [

# ============================================================ WHERE TO STAY
{
 "city":"berlin", "slug":"where-to-stay-in-berlin", "order":2,
 "title":"Where to Stay in Berlin: Best Areas & Hotels",
 "kicker":"Berlin · Where to stay",
 "dek":"Six neighborhoods that feel like different cities — from Mitte's monuments to Neukölln's Arab Street — and exactly where to book in each.",
 "description":"Where to stay in Berlin: Mitte, Kreuzberg, Neukölln, Prenzlauer Berg, Friedrichshain and Charlottenburg compared, with real hotels for every budget.",
 "read":"9 min", "updated":"July 2026",
 "related":["where-to-eat-in-berlin","best-things-to-do-in-berlin","3-days-in-berlin"],
 "blocks":[
  {"t":"lead","html":"Berlin is big enough that picking the wrong neighborhood costs you real time — an hour each way on the U-Bahn adds up fast over a long weekend. Six areas cover almost every visitor's needs, and one of them is nothing like what a first-time guide tells you to expect. Here's who each is actually for, and the specific hotels worth booking in each."},
  {"t":"h2","text":"The six neighborhoods, honestly"},
  {"t":"compare","head":["Area","Best for","Good to know"],
   "rows":[
     ["<strong>Mitte</strong>","First-timers who want to walk to everything","Brandenburg Gate, Museum Island and the TV Tower are all walkable or one stop away — but it's the most touristy district, and the priciest: roughly €80–450/night."],
     ["<strong>Kreuzberg</strong>","Street art, multicultural food, late-night bars","Berlin's counterculture heart, genuinely lively after dark. Hotels run roughly €70–150/night."],
     ["<strong>Neukölln</strong>","The Sonnenallee food crawl, best-value eating","Once overlooked, now home to Berlin's creative scene, Tempelhofer Feld (the old airport-turned-park), and our featured Arab Street food crawl. Fewer big 'sights' on your doorstep, but a short ride from Mitte."],
     ["<strong>Prenzlauer Berg</strong>","Families, a slower pace, Sunday flea markets","Leafy and historic, cafés everywhere. Roughly €90–170/night."],
     ["<strong>Friedrichshain</strong>","Nightlife — Berghain and East Side Gallery on your doorstep","Berlin's cheapest hostel beds, dorms from around €24/night. Expect noise if you're near the clubs."],
     ["<strong>Charlottenburg</strong>","West Berlin elegance, Kurfürstendamm shopping","Charlottenburg Palace and upscale hotels, roughly €150–400+/night. Furthest from the Mitte sights."],
   ],
   "cap":"First trip and want to walk everywhere → Mitte. Building your trip around the food crawl → Neukölln or Kreuzberg."},
  {"t":"p","html":"Mitte is the safe, obvious choice, and for a first trip it's a genuinely good one. But if the Sonnenallee food crawl in our <a class='inline' href='/berlin/where-to-eat-in-berlin/'>Berlin food guide</a> is part of your plan, basing yourself in Neukölln or neighboring Kreuzberg turns a special trip across town into a ten-minute walk."},
  {"t":"h2","text":"Where to actually book"},
  {"t":"p","html":"Real, bookable hotels across the price range — budget capsules to design boutiques — pulled from live Booking.com listings, not a wishlist."},
  {"t":"stays","items":[
    {"name":"Heart of Gold Hostel & Capsules Berlin","area":"Mitte","band":"Budget/hostel","program":"booking","query":"Heart of Gold Hostel Berlin",
     "blurb":"Capsule-hotel-style bunks dead in the center of Mitte — the cheapest tier that still feels designed, not just cheap."},
    {"name":"ibis Berlin Hauptbahnhof","area":"Mitte","band":"Budget","program":"booking","query":"ibis Berlin Hauptbahnhof",
     "blurb":"A reliable chain hotel steps from the main train station — the unglamorous, always-works option if you land late or leave early."},
    {"name":"Casa Camper Berlin","area":"Mitte","band":"Mid-range design","program":"booking","query":"Casa Camper Berlin",
     "blurb":"Central and design-forward, with strong guest ratings — a step up from the chain hotels without boutique prices."},
    {"name":"Locke at East Side Gallery","area":"Friedrichshain-Kreuzberg","band":"Mid-range (aparthotel)","program":"booking","query":"Locke at East Side Gallery Berlin",
     "blurb":"An aparthotel right by the East Side Gallery, with the Friedrichshain nightlife strip on your doorstep — useful if you want a kitchen."},
    {"name":"The Mandala Berlin","area":"Mitte · Potsdamer Platz","band":"Boutique/upscale","program":"booking","query":"The Mandala Hotel Berlin Potsdamer Platz",
     "blurb":"An all-suite design hotel near Potsdamer Platz, for when you want space and polish without leaving the center."},
    {"name":"Wilmina Hotel","area":"Charlottenburg-Wilmersdorf","band":"Boutique","program":"booking","query":"Wilmina Hotel Berlin",
     "blurb":"A repurposed historic building turned quietly stylish hotel in the West — the pick for a calmer, more grown-up Berlin base."},
  ]},
  {"t":"book","head":"Compare Berlin stays","html":"Booking.com has the deepest Berlin listings across every neighborhood — compare the areas above side by side before you commit.","program":"booking","query":"Berlin","label":"See Berlin stays on Booking"},
  {"t":"h2","text":"If Sonnenallee is the whole point of your trip"},
  {"t":"tip","head":"Base yourself near the food","html":"Neukölln puts you inside walking distance of the Arab Street itself; Kreuzberg next door is nearly as close, with its own street-food and bar scene besides. Both beat commuting in from Mitte for an evening crawl. See the <a class='inline' href='/berlin/where-to-eat-in-berlin/'>full Sonnenallee guide</a> before you pick a hotel."},
  {"t":"h2","text":"When to book"},
  {"t":"ul","items":[
    "<strong>May through September</strong> is Berlin's best-weather window — book two to four weeks ahead in peak summer (July–August), when the mild-weather crowds are thickest.",
    "<strong>The Berlin Marathon</strong>, run through the city in late September, is one of the world's biggest marathons and fills hotels citywide — check the date before you book if you're not running it.",
    "<strong>Christmas markets (late November–December)</strong> bring their own demand despite the cold; book ahead if that's your trip.",
    "<strong>Winter (December–February)</strong> runs genuinely cold, with highs around 3°C and snow common into March — the trade-off is the thinnest crowds and the lowest rates of the year.",
  ]},
  {"t":"h2","text":"Getting from your hotel to the airport"},
  {"t":"p","html":"Berlin Brandenburg Airport (BER) sits about 18km southeast of the center. Wherever you stay, the Airport Express (FEX) reaches Hauptbahnhof in roughly 22 minutes, running every 15 minutes; S-Bahn lines S9 and S45 also connect, with S45 conveniently passing through Neukölln on its way in. The station runs 24/7, so a late landing or an early flight out isn't a problem."},
 ],
 "faq":[
   ("Which area of Berlin is best for first-time visitors?",
    "Mitte — it's central, walkable to Brandenburg Gate, Museum Island and the TV Tower, and has the widest range of hotels. It's also the most touristy and most expensive of the six areas, roughly €80–450 a night."),
   ("Should I stay in Neukölln instead of Mitte?",
    "Only if the Sonnenallee food crawl (see our <a class='inline' href='/berlin/where-to-eat-in-berlin/'>food guide</a>) is a real priority, or you want Berlin's best-value neighborhood over walkability to the big monuments. Many visitors split the difference and stay in neighboring Kreuzberg, close to both Neukölln and central Berlin."),
   ("How much does a hotel in Berlin cost?",
    "Budget hostel-style rooms — like Heart of Gold's capsules in Mitte — sit at the cheap end of Mitte's roughly €80–450/night range; comfortable mid-range hotels run about €70–170/night in Kreuzberg or Prenzlauer Berg; boutique and upscale stays in Mitte or Charlottenburg run €150–450+/night depending on the season."),
 ],
},

# ============================================================ THINGS TO DO
{
 "city":"berlin", "slug":"best-things-to-do-in-berlin", "order":3,
 "title":"Best Things to Do in Berlin",
 "kicker":"Berlin · Do",
 "dek":"The monuments worth the walk, the one ticket you must book ahead, and the Cold War history that's more than a photo op.",
 "description":"What to do in Berlin: Brandenburg Gate, the Reichstag dome, East Side Gallery, Museum Island, Checkpoint Charlie and the Cold War tours worth booking.",
 "read":"10 min", "updated":"July 2026",
 "related":["where-to-eat-in-berlin","where-to-stay-in-berlin","3-days-in-berlin"],
 "blocks":[
  {"t":"lead","html":"Berlin's list of essentials is long, spread across a genuinely big city, and complicated by exactly one thing: the best single ticket in town needs to be booked before you land, not after you arrive. Sort that first, and the rest of this list falls into place on foot and by U-Bahn."},
  {"t":"h2","text":"Book this first: the Reichstag glass dome"},
  {"t":"p","html":"The <strong>Reichstag's glass dome</strong> is free to enter and gives you a 360° spiral walk over the government quarter and the city beyond — but only with a reserved time slot, and slots fill up. Some dates in 2026 close the dome to visitors entirely, so this is the one thing on this list worth locking in before you plan the rest of your day."},
  {"t":"book","head":"Reserve your Reichstag dome slot","html":"Free entry, but a confirmed time slot is essential — guided Reichstag and government-district tours bundle the reservation with a guide who explains what you're looking at.","program":"gyg","query":"Reichstag dome Berlin","label":"See Reichstag tours"},
  {"t":"h2","text":"The free monuments — no ticket, ever"},
  {"t":"p","html":"Three of Berlin's most essential sights cost nothing and are open whenever you show up:"},
  {"t":"do","items":[
    {"name":"Brandenburg Gate","tag":"Free, always open",
     "blurb":"The city's defining monument, floodlit after dark. Walk past it once during the day and once at night — it reads completely differently both times."},
    {"name":"East Side Gallery","tag":"Free, always open",
     "blurb":"1.3km of the Berlin Wall repainted by more than a hundred international artists, right along the river in Friedrichshain. Best walked slowly, early or late to dodge the crowds."},
    {"name":"Holocaust Memorial","tag":"Free, always open",
     "blurb":"The Memorial to the Murdered Jews of Europe — 2,711 concrete slabs of varying height, right by the Brandenburg Gate and Tiergarten. Sobering, and worth the twenty minutes even on a tight schedule."},
  ]},
  {"t":"h2","text":"Museum Island: five museums, one very old island"},
  {"t":"p","html":"<strong>Museumsinsel</strong> is a UNESCO World Heritage Site holding five major museums in one small footprint: the Pergamon, the Neues, the Altes, the Alte Nationalgalerie and the Bode. A combined pass covers all five and saves both money and queueing versus buying tickets one museum at a time."},
  {"t":"warn","head":"Check the Pergamon before you plan around it","html":"The Pergamon Museum's most famous hall — home of the Pergamon Altar — has been closed for a long-term renovation since 2023, with parts of the museum expected to stay closed for years. The rest of Museum Island is unaffected, but confirm what's actually open before you build a day specifically around the Pergamon."},
  {"t":"book","head":"Skip the line on Museum Island","html":"A combined museum pass is the efficient way to see more than one of the five — worth it even if you only manage two museums in an afternoon.","program":"gyg","query":"Museum Island Berlin pass","label":"See Museum Island tickets"},
  {"t":"h2","text":"Cold War Berlin: Checkpoint Charlie and the wall that isn't there anymore"},
  {"t":"p","html":"<strong>Checkpoint Charlie</strong>, the most famous Cold War border crossing, is now a small open-air site and museum — worth five minutes on its own, but genuinely comes alive paired with a guided walking tour that explains what actually happened on the ground you're standing on. If Checkpoint Charlie's tourist-market feel undersells it for you, the <strong>Berlin Wall Memorial on Bernauer Straße</strong> is the quieter, more substantial alternative: a preserved stretch of the former death strip with a documentation center."},
  {"t":"do","items":[
    {"name":"Checkpoint Charlie","tag":"Free to view",
     "blurb":"The famous crossing point, reduced to a guardhouse and signage today — the history is in what you bring to it, or in the tour you pair it with."},
    {"name":"Cold War & Third Reich walking tours","tag":"Book ahead","program":"gyg","query":"Berlin Cold War walking tour","label":"See walking tours",
     "blurb":"Consistently one of Berlin's best-selling bookings, and for good reason — a good guide turns scattered plaques and a rebuilt guardhouse into an actual narrative."},
  ]},
  {"t":"h2","text":"The view, and the park underneath it"},
  {"t":"p","html":"The <strong>Berlin TV Tower (Fernsehturm)</strong> at Alexanderplatz has the observation deck and revolving restaurant that give you the skyline view the Reichstag dome can't — time it for sunset if you can. Coming from Brandenburg Gate toward Charlottenburg, cut through <strong>Tiergarten</strong>, Berlin's answer to Central Park, past the gold-topped Victory Column (Siegessäule) at its center — it turns a transit stop into an actual walk."},
  {"t":"h2","text":"After dark: Berghain and the wider club scene"},
  {"t":"p","html":"Berlin's techno reputation is real, and <strong>Berghain</strong> in Friedrichshain is its most famous address — self-described 'world capital of techno,' with a door policy that's near-mythical and entirely unpredictable. You can't book your way past it, and we won't pretend otherwise. The wider clubbing scene in Kreuzberg and Friedrichshain is strong on its own if the door doesn't go your way."},
  {"t":"h2","text":"At a glance: what's free and what needs a ticket"},
  {"t":"compare","head":["Sight","Cost","Book ahead?"],
   "rows":[
     ["Brandenburg Gate","Free","No"],
     ["Reichstag glass dome","Free entry","Yes — essential, slots fill"],
     ["East Side Gallery","Free","No"],
     ["Museum Island (5 museums)","Paid, combined pass available","Recommended"],
     ["Checkpoint Charlie","Free to view the site","No"],
     ["Cold War / Third Reich walking tour","Paid","Recommended"],
     ["Berlin TV Tower","Paid","Optional — helps for sunset slots"],
     ["Holocaust Memorial","Free","No"],
   ],
   "cap":"Book the Reichstag dome first — it's the only one on this list with real availability risk."},
  {"t":"book","head":"Ready to book the essentials","html":"GetYourGuide covers the Reichstag dome, Museum Island passes and the best-reviewed Cold War walking tours in one place — worth comparing before you commit to a specific time.","program":"gyg","query":"Berlin","label":"Browse Berlin tours & tickets"},
 ],
 "faq":[
   ("Do I need to book the Reichstag dome in advance?",
    "Yes. Entry is free but only with a reserved time slot, and slots fill up — some 2026 dates close the dome to visitors entirely. Book before you finalize the rest of your day, ideally before you land."),
   ("What's the difference between East Side Gallery and Checkpoint Charlie?",
    "East Side Gallery is 1.3km of the actual Berlin Wall, painted by international artists and free to walk anytime. Checkpoint Charlie was a border crossing, not a wall segment — today it's a small guardhouse-and-museum site, best paired with a guided Cold War walking tour for context."),
   ("Is the Holocaust Memorial free to visit?",
    "Yes — the Memorial to the Murdered Jews of Europe is free and open at all times, right by the Brandenburg Gate and the edge of Tiergarten."),
 ],
},

# ============================================================ 3-DAY ITINERARY
{
 "city":"berlin", "slug":"3-days-in-berlin", "order":4,
 "title":"3 Days in Berlin: The Perfect Itinerary",
 "kicker":"Berlin · Itinerary",
 "dek":"A day-by-day plan that covers the monuments, the Wall, and the Sonnenallee food crawl most Berlin itineraries miss entirely.",
 "description":"The perfect 3-day Berlin itinerary: historic Mitte, the Wall and Kreuzberg, then a choice of Museum Island or the Sonnenallee food crawl and nightlife.",
 "read":"9 min", "updated":"July 2026",
 "related":["where-to-eat-in-berlin","where-to-stay-in-berlin","best-things-to-do-in-berlin"],
 "blocks":[
  {"t":"lead","html":"Three days is enough to cover Berlin's essential monuments, its Cold War history, and — because almost no other itinerary sends you here — an afternoon on Sonnenallee, the Levantine food street that's become one of the city's defining food scenes. Here's how to sequence it."},
  {"t":"compare","head":["Day","Focus","Don't miss"],
   "rows":[
     ["<strong>Day 1</strong>","Historic Mitte","The Reichstag dome — book it before you land"],
     ["<strong>Day 2</strong>","The Wall, the Cold War, Kreuzberg","East Side Gallery in the morning, before the crowds"],
     ["<strong>Day 3</strong>","Museum Island or the Sonnenallee food crawl","Whichever you choose, don't try to do both in one day"],
   ],
   "cap":"Full detail on each day below — including where to book ahead."},
  {"t":"h2","text":"Day 1: Historic Mitte"},
  {"t":"p","html":"Start at the <strong>Brandenburg Gate</strong>, free and open whenever you arrive. From there it's a short walk to the <strong>Reichstag glass dome</strong> — assuming you booked a slot before you landed (see our <a class='inline' href='/berlin/best-things-to-do-in-berlin/'>things-to-do guide</a> for why that matters), the 360° spiral walk is worth building your morning around. The <strong>Holocaust Memorial</strong> sits right between the two, free and always open — give it twenty honest minutes. Spend the afternoon on <strong>Museum Island</strong>, and end the day at the <strong>TV Tower</strong> for sunset over Alexanderplatz."},
  {"t":"tip","head":"Book before you land, not on the day","html":"The Reichstag dome is the one reservation on this whole itinerary that can actually fall through — some 2026 dates close it to visitors entirely. Lock in a slot as soon as you have travel dates."},
  {"t":"book","head":"Sort Day 1's tickets in one go","html":"Reichstag dome slots and Museum Island's combined pass are both worth booking ahead of arrival.","program":"gyg","query":"Berlin","label":"See Reichstag & Museum Island tickets"},
  {"t":"h2","text":"Day 2: The Wall, the Cold War, and Kreuzberg"},
  {"t":"p","html":"Walk the <strong>East Side Gallery</strong> in the morning — 1.3km of the Berlin Wall repainted by more than a hundred artists, quieter before midday. From there, head to <strong>Checkpoint Charlie</strong>; on its own it's five minutes, so pair it with a guided Cold War or Third Reich walking tour, consistently one of Berlin's best-selling bookings for a reason. Spend the rest of the afternoon and evening in <strong>Kreuzberg</strong> — Berlin's counterculture heart, with legendary street food and a strong craft-beer and late-bar scene to close out the day."},
  {"t":"book","head":"Book the walking tour ahead","html":"Good Cold War guides sell out their better time slots in high season — worth booking a day or two ahead rather than hoping to walk up.","program":"gyg","query":"Berlin Cold War walking tour","label":"See walking tours"},
  {"t":"h2","text":"Day 3: choose your ending"},
  {"t":"p","html":"Your third day is the one place we'd actually let you pick your own adventure — both options below are a full day on their own, so don't try to combine them."},
  {"t":"h3","text":"Option A: Museum Island, properly this time"},
  {"t":"p","html":"If Day 1 only gave you time for one or two of the five Museum Island museums, come back and do it right: the Neues, the Altes, the Alte Nationalgalerie and the Bode are all worth a slower look than a single afternoon allows. Just confirm what's actually open in the Pergamon before you build the day around it — see our <a class='inline' href='/berlin/best-things-to-do-in-berlin/'>things-to-do guide</a> for the current caveat."},
  {"t":"h3","text":"Option B: The Sonnenallee food crawl + nightlife"},
  {"t":"p","html":"Take the S-Bahn or U7 into Neukölln for the afternoon and work through our <a class='inline' href='/berlin/where-to-eat-in-berlin/'>Sonnenallee food crawl</a> — Syrian shawarma, Yemeni cooking, Palestinian falafel and Damascene sweets, all within a few blocks of each other. From there, Friedrichshain and Kreuzberg's club scene is a short ride away if you want to end the trip properly; just know that Berghain's door policy is entirely its own thing, and no amount of planning gets you past it."},
  {"t":"h2","text":"Where to base yourself for these three days"},
  {"t":"p","html":"<strong>Mitte</strong> puts Days 1 and 2 within walking distance and is the easiest default — see our <a class='inline' href='/berlin/where-to-stay-in-berlin/'>full stays guide</a> for specific hotels. If Day 3's food crawl is the real priority, basing yourself in <strong>Neukölln</strong> or <strong>Kreuzberg</strong> instead turns that afternoon into a ten-minute walk rather than a special trip across town."},
  {"t":"h2","text":"Practical notes for the three days"},
  {"t":"ul","items":[
    "<strong>From the airport:</strong> BER sits about 18km out; the Airport Express (FEX) reaches Hauptbahnhof in roughly 22 minutes, running every 15 minutes, so you can land and start Day 1 the same afternoon.",
    "<strong>Getting around:</strong> the BVG network (U-Bahn, S-Bahn, trams, buses) covers all three days easily — Mitte, Kreuzberg and Neukölln are also genuinely walkable between stops.",
    "<strong>The Berlin WelcomeCard</strong> bundles unlimited transit with museum and attraction discounts across multi-day options — price it against single tickets for your exact plan before buying.",
    "<strong>Best timing:</strong> May through September gives you the mildest weather; aim for May, September or early October for that same mild window with thinner crowds.",
  ]},
  {"t":"book","head":"Book the whole itinerary's must-reserves","html":"Reichstag dome, Museum Island pass, and the Cold War walking tour — the three things on this itinerary actually worth locking in ahead of time.","program":"gyg","query":"Berlin","label":"Browse Berlin tours & tickets"},
 ],
 "faq":[
   ("Is 3 days enough for Berlin?",
    "Yes, for the essentials — Brandenburg Gate, the Reichstag, Museum Island, the Wall and one full afternoon on Sonnenallee. Give it four or five days if you want to add a club night, a slower museum pace, or both Day 3 options instead of just one."),
   ("Which day should I do the Sonnenallee food crawl?",
    "Day 3 works best in this itinerary, after the core monuments and Cold War history are done — but it's flexible. If food is your priority over a second museum day, swap it in earlier without disrupting Days 1 or 2."),
   ("What should I book before I land in Berlin?",
    "The Reichstag dome, first — it has real availability risk and some dates close entirely. A Museum Island pass and a Cold War walking tour slot are worth booking a few days ahead too, though they're less likely to sell out completely."),
 ],
},

]
