# -*- coding: utf-8 -*-
# BERLIN — sights-and-essentials hub, plus the one thing no other Berlin guide
# leads with: Sonnenallee, Neukölln's "Arab Street" food crawl.
# All facts sourced from research/city-berlin.md (our own 30-business
# Sonnenallee/Neukölln dataset + cross-checked web research, July 2026).

CITY = {
 "id": "berlin",
 "intro_blocks": [
  {"t":"lead","html":"Berlin gets sold as Cold War history and techno myths, and both are real. But the thing that actually defines the city right now is a street most visitors never hear about: <strong>Sonnenallee</strong>, in Neukölln, which Berliners have nicknamed <strong>the Arab Street</strong>. This guide covers both halves of Berlin — the sights everyone comes for, and the food street almost nobody sends you to."},
  {"t":"p","html":"Here's the part that makes us different: every business we feature in this city sits on or within two blocks of Sonnenallee. Its Arab character goes back to 1975, when Lebanese refugees fleeing the civil war began settling North Neukölln; Syrian, Palestinian and Yemeni communities followed in the decades after. Neukölln today counts roughly 33,000 Arab residents — about a quarter of Berlin's entire Arab population — and it's one of the largest concentrations of Levantine food outside the Middle East itself, all walkable in an afternoon. We go deep on it in our <a class='inline' href='/berlin/where-to-eat-in-berlin/'>Sonnenallee food crawl</a>; here are seven places to start."},
  {"t":"eats","ranked":True,"items":[
    {"name":"Azzam Restaurant","slug":"azzam-restaurant","area":"Sonnenallee, Neukölln",
     "blurb":"The flagship of the strip: Syrian shawarma and famously gigantic group platters that regulars say are simply a different thing from the shops around it."},
    {"name":"Sana'a Al Yemen","slug":"sanaa-al-yemen","area":"Sonnenallee, Neukölln",
     "blurb":"Yemeni cooking in genuinely generous portions — demand got them a bigger space, and it shows."},
    {"name":"Al Hanan","slug":"al-hanan-falafel","area":"Sonnenallee, Neukölln",
     "blurb":"Falafel one reviewer flatly called the best in Europe, and more than one puts it in their personal world top three."},
    {"name":"Falafel Jakoub","slug":"falafel-jakoub","area":"Weserstraße, Neukölln",
     "blurb":"A falafel sandwich built with mango and hazelnut sauce, plus a shawarma-and-baba-ganoush wrap you won't see written down anywhere else."},
    {"name":"Malek Al Konafeh","slug":"malek-al-konafeh","area":"Sonnenallee, Neukölln",
     "blurb":"The street's kunafa specialist — crunchy or soft, pistachio-topped — alongside proper Arabic ice cream."},
    {"name":"Al-Madina Supermarkt","slug":"al-madina-markt","area":"Sonnenallee, Neukölln",
     "blurb":"A Levantine grocery for spices, produce, cheese and nuts that homesick regulars call, more than once, 'memories of homeland.'"},
    {"name":"Fleischerei Yousef Abu Haija","slug":"abu-haija-fleischerei","area":"Sonnenallee, Neukölln",
     "blurb":"A halal butcher regulars call the best fresh meat on the street — handy if your stay has a kitchen."},
  ]},
  {"t":"h2","text":"Where to stay"},
  {"t":"p","html":"<strong>Mitte</strong> is the easy first-timer base — Brandenburg Gate, Museum Island and the TV Tower are all walkable or a stop away, though it's the most touristy district too. <strong>Kreuzberg</strong> brings street art, multicultural food and late-night bars; <strong>Neukölln</strong> next door is our featured food ground, once overlooked and now genuinely the best-value district for authentic eating (plus Tempelhofer Feld, the old airport-turned-park). <strong>Prenzlauer Berg</strong> is leafy and family-friendly, <strong>Friedrichshain</strong> is the nightlife capital with Berlin's cheapest hostel beds, and <strong>Charlottenburg</strong> is West Berlin elegance with upscale hotels."},
  {"t":"stays","items":[
    {"name":"Heart of Gold Hostel & Capsules Berlin","area":"Mitte","band":"Budget/hostel","program":"booking","query":"Heart of Gold Hostel Berlin",
     "blurb":"Capsule-hotel-style bunks dead in the center of Mitte — the cheapest tier that still feels designed, not just cheap."},
    {"name":"Locke at East Side Gallery","area":"Friedrichshain-Kreuzberg","band":"Mid-range (aparthotel)","program":"booking","query":"Locke at East Side Gallery Berlin",
     "blurb":"An aparthotel right by the East Side Gallery, with the Friedrichshain nightlife strip on your doorstep."},
    {"name":"The Mandala Berlin","area":"Mitte · Potsdamer Platz","band":"Boutique/upscale","program":"booking","query":"The Mandala Hotel Berlin Potsdamer Platz",
     "blurb":"An all-suite design hotel near Potsdamer Platz, for when you want space and polish without leaving the center."},
    {"name":"Wilmina Hotel","area":"Charlottenburg-Wilmersdorf","band":"Boutique","program":"booking","query":"Wilmina Hotel Berlin",
     "blurb":"A repurposed historic building turned quietly stylish hotel in the West — the pick for a calmer, more grown-up Berlin base."},
  ]},
  {"t":"book","head":"Compare Berlin stays","html":"Booking.com has the deepest Berlin listings across every neighborhood and budget — compare the areas above side by side before you commit.","program":"booking","query":"Berlin","label":"See Berlin stays on Booking"},
  {"t":"h2","text":"What to do"},
  {"t":"p","html":"Berlin's essentials are spread across a big city, and one of them needs booking ahead — sort that first and the rest falls into place:"},
  {"t":"do","items":[
    {"name":"Brandenburg Gate","tag":"Free, always open",
     "blurb":"The city's defining monument, floodlit after dark. Walk past it as many times as you like — it's free every time."},
    {"name":"Reichstag Glass Dome","tag":"Book ahead","program":"gyg","query":"Reichstag dome Berlin","label":"See Reichstag tours",
     "blurb":"A 360° spiral walk over the city, free to enter but only with a reserved slot — some 2026 dates close to visitors entirely, so lock in a time before you plan the rest of the day."},
    {"name":"East Side Gallery","tag":"Free, always open",
     "blurb":"1.3km of the Berlin Wall repainted by more than a hundred artists — outdoors, free, and best walked slowly."},
    {"name":"Museum Island","tag":"UNESCO","program":"gyg","query":"Museum Island Berlin pass","label":"See Museum Island tickets",
     "blurb":"Five major museums — Pergamon, Neues, Altes, Alte Nationalgalerie, Bode — on one small island; a combined pass saves both money and queueing."},
    {"name":"Berlin TV Tower (Fernsehturm)","tag":"Alexanderplatz",
     "blurb":"The observation deck gives you the skyline view the Reichstag dome can't — worth timing for sunset."},
    {"name":"Checkpoint Charlie & a Cold War walking tour","tag":"History","program":"gyg","query":"Berlin Cold War walking tour","label":"See walking tours",
     "blurb":"The famous crossing point is five minutes on its own; pair it with a guided Cold War or Third Reich walking tour — consistently one of Berlin's best-selling bookings — for the history that isn't on a placard."},
  ]},
  {"t":"h2","text":"Getting around"},
  {"t":"p","html":"Berlin Brandenburg Airport (BER) sits about 18km southeast of the center. The Airport Express (FEX) runs every 15 minutes to Hauptbahnhof in roughly 22 minutes, and S-Bahn lines S9 and S45 also connect — S45 conveniently passes through Neukölln and Tempelhof on its way in. The station runs 24/7. Once you're in the city, the BVG network (U-Bahn, S-Bahn, trams and buses) covers everywhere, and Berlin is flat enough to genuinely get around by bike. For Sonnenallee specifically: it has its own S-Bahn station, or take the U7 to Karl-Marx-Straße or Rathaus Neukölln and walk in. Sightseeing hard across several days? The Berlin WelcomeCard bundles unlimited transit with museum and attraction discounts — worth pricing against single tickets before you commit."},
  {"t":"tip","head":"Best time to visit","html":"May through September is the sweet spot — summer highs run 22–25°C, and May, September and early October give you nearly the same mild weather as peak summer minus the July–August crowds. Winter runs genuinely cold (highs near 3°C, snow common December–March), though if Christmas markets are your thing, that's a reason to come anyway."},
 ],
 "faq": [
  ("How many days do you need in Berlin?",
   "Three days covers the core sights — Brandenburg Gate, the Reichstag, Museum Island, East Side Gallery — plus a proper afternoon on Sonnenallee for the food crawl. Give it four or five if you want a club night, a full museum day, or a slower pace through Neukölln and Kreuzberg."),
  ("What is Sonnenallee, and is it worth a special trip?",
   "Sonnenallee is a street through Neukölln that's been known as Berlin's 'Arab Street' since Lebanese refugees began settling there in 1975, later joined by Syrian, Palestinian and Yemeni communities. Today it's one of the largest concentrations of Levantine food outside the Middle East — shawarma, falafel, kunafa and halal butchers, block after block. It's a short train ride from central Berlin and genuinely worth a dedicated afternoon; see our <a class='inline' href='/berlin/where-to-eat-in-berlin/'>full food crawl</a>."),
  ("Which neighborhood should I stay in for Berlin?",
   "Mitte if it's your first trip and you want to walk to the big sights. Kreuzberg or Neukölln if you want nightlife, street food and a more local feel — Neukölln also puts you steps from Sonnenallee. Charlottenburg is quieter and more upscale, and Friedrichshain has the cheapest hostel beds and the best-known clubs."),
 ],
}

PAGES = [

# ============================================================ WHERE TO EAT
{
 "city":"berlin", "slug":"where-to-eat-in-berlin", "order":1,
 "title":"The Best Middle Eastern Food in Berlin: A Sonnenallee Food Crawl",
 "kicker":"Berlin · Food",
 "dek":"Syrian shawarma, Yemeni cooking, Palestinian falafel and Damascene sweets — a walkable crawl down Sonnenallee, the street Berliners call the Arab Street.",
 "description":"A food crawl down Sonnenallee, Berlin's 'Arab Street' in Neukölln: Syrian shawarma, Yemeni food, falafel and Damascene sweets, stop by stop.",
 "read":"8 min", "updated":"July 2026",
 "related":[],
 "blocks":[
  {"t":"lead","html":"Berlin's food reputation runs on currywurst and döner, and both earn it. But the best Middle Eastern food outside the Middle East itself is a short train ride from the Brandenburg Gate, on one street in Neukölln most visitors never hear about. This is a food crawl down Sonnenallee — Syrian shawarma, Palestinian falafel, Yemeni cooking, Damascene sweets, halal butchers and Levantine grocers, roughly in walking order."},
  {"t":"h2","text":"Sonnenallee: how a Beirut street ended up in Neukölln"},
  {"t":"p","html":"Berliners have called this street <strong>the Arab Street</strong> for years — a nickname common enough that Middle East Eye, The National and the South China Morning Post have all covered it. It started in 1975, when Lebanese refugees fleeing the civil war settled North Neukölln; Syrian, Palestinian and Yemeni communities followed in the decades after. Neukölln today has roughly 33,000 Arab residents — about a quarter of Berlin's entire Arab population — and Middle Eastern-origin residents make up close to 18% (around 55,000 people) of the borough."},
  {"t":"p","html":"We know this street because we mapped it ourselves: our own count of roughly 30 businesses on and just off Sonnenallee is one of the densest, most self-contained Arab strips we've seen anywhere — a halal butcher next to a goldsmith next to a falafel counter next to a bridal shop. This guide covers the 15 food, sweets and grocery spots from that list, in the order you'd actually walk them."},
  {"t":"h2","text":"Five words worth knowing before you go"},
  {"t":"ul","items":[
    "<strong>Shawarma</strong> — meat shaved off a vertical spit, wrapped or plated.",
    "<strong>Falafel</strong> — fried chickpea patties, the vegetarian backbone of every menu here.",
    "<strong>Kunafa (knafeh)</strong> — syrup-soaked cheese pastry, usually pistachio-topped.",
    "<strong>Manakish</strong> — Syrian flatbread, often topped with za'atar or cheese.",
    "<strong>Warbat</strong> — a warm, cream-filled pastry, closer to a cream puff than baklava.",
  ]},
  {"t":"h2","text":"The mains: shawarma, falafel, grills and Yemeni cooking"},
  {"t":"p","html":"Seven stops, all within a few minutes of each other on or just off Sonnenallee. You will not manage all seven in one sitting — treat this as a menu, not an itinerary."},
  {"t":"eats","ranked":True,"items":[
    {"name":"Azzam Restaurant","slug":"azzam-restaurant","area":"Sonnenallee, Neukölln",
     "blurb":"The flagship of the street. Syrian shawarma and famously massive group platters — reviewers consistently say it's simply a different operation from the shawarma shops around it."},
    {"name":"Shawarma Albaik","slug":"shawarma-albaik","area":"Sonnenallee, Neukölln",
     "blurb":"Beef and chicken shawarma wraps done exactly right — reviewers call it a genuine fixture of 'what is called the Arab street in Berlin.'"},
    {"name":"Falafel Jakoub","slug":"falafel-jakoub","area":"Weserstraße, Neukölln",
     "blurb":"A falafel sandwich sauced with mango and hazelnut, plus a shawarma-and-baba-ganoush wrap that's just as worth ordering."},
    {"name":"Sana'a Al Yemen","slug":"sanaa-al-yemen","area":"Sonnenallee, Neukölln",
     "blurb":"Yemeni specialties in genuinely generous portions; demand got them a bigger space, which tells you what you need to know."},
    {"name":"Falfool","slug":"falfool","area":"Sonnenallee, Neukölln",
     "blurb":"Falafel and baked goods that multiple reviewers independently call a hidden gem — easy to walk past, worth stopping for."},
    {"name":"Al Hanan","slug":"al-hanan-falafel","area":"Sonnenallee, Neukölln",
     "blurb":"One reviewer's 'best falafel in Europe'; another puts it in their personal world top three. Both are believable after one bite."},
    {"name":"Al-Karam Grill","slug":"al-karam-grill","area":"Sonnenallee, Neukölln",
     "blurb":"Mixed grills cooked fresh to order right in front of you — go when you want something charred and immediate."},
  ]},
  {"t":"h2","text":"Sweets and bakery: kunafa, baklava, warbat, manakish"},
  {"t":"p","html":"Save room. This is the part of the crawl people talk about after they've gone home."},
  {"t":"eats","ranked":True,"items":[
    {"name":"Malek Al Konafeh","slug":"malek-al-konafeh","area":"Sonnenallee, Neukölln",
     "blurb":"The kunafa specialist — crunchy or soft, pistachio-topped — plus a proper Arabic ice cream to go with it. Syrian sweets, done seriously."},
    {"name":"Habibi Süßigkeiten","slug":"habibi-suessigkeiten","area":"Erkstraße, Neukölln",
     "blurb":"Arabic and Turkish sweets with warbat — a cream-puff pastry — served still warm, alongside coffee strong enough to justify the sugar."},
    {"name":"El Daia","slug":"el-daia","area":"Sonnenallee, Neukölln",
     "blurb":"A bakery turning out manakish, Syrian flatbread, fresh from the oven — reviewers call it tasty and genuinely underpriced."},
  ]},
  {"t":"h2","text":"Stock up like a local: markets and halal butchers"},
  {"t":"p","html":"If your stay has a kitchen, or you just want to take a piece of the street home with you, this is where regulars actually shop."},
  {"t":"eats","ranked":True,"items":[
    {"name":"Al-Madina Supermarkt","slug":"al-madina-markt","area":"Sonnenallee, Neukölln",
     "blurb":"A proper Levantine grocery — spices, produce, cheese, nuts — that reviewers describe, more than once, as 'memories of homeland.'"},
    {"name":"Supermarkt Alscham","slug":"alscham-markt","area":"Sonnenallee, Neukölln",
     "blurb":"A neighborhood Arab grocery with the kind of warm, personal service that gets reviewers calling the staff 'my neighbours.'"},
    {"name":"Fleischerei Yousef Abu Haija","slug":"abu-haija-fleischerei","area":"Sonnenallee, Neukölln",
     "blurb":"A halal butcher reviewers call the best fresh meat on the street — good for BBQ cuts if you're cooking."},
    {"name":"Fleischerei Ali Lobany","slug":"ali-lobany-fleischerei","area":"Sonnenallee, Neukölln",
     "blurb":"Chicken, beef and lamb from a halal butcher whose owner personally replies to every single review — a good sign of how seriously he takes the shop."},
    {"name":"Al Amana Fleischerei","slug":"al-amana-fleischerei","area":"Sonnenallee, Neukölln",
     "blurb":"A halal butcher with an adjoining mini-market — mutton, beef, chicken and fresh produce side by side, one stop."},
  ]},
  {"t":"h2","text":"What to order where"},
  {"t":"compare","head":["Order this","Where","Why it's the move"],
   "rows":[
     ["<strong>Giant shawarma platter</strong>","Azzam Restaurant","Built for groups. 4.8★, 6,600+ reviews."],
     ["<strong>Mango-hazelnut falafel</strong>","Falafel Jakoub","A sauce nobody else on the strip uses."],
     ["<strong>Yemeni platter</strong>","Sana'a Al Yemen","Generous portions — go hungry."],
     ["<strong>Falafel, if you only eat one</strong>","Al Hanan","Reviewers rank it among Europe's best."],
     ["<strong>Kunafa (knafeh)</strong>","Malek Al Konafeh","Crunchy or soft, pistachio-topped."],
     ["<strong>Warm warbat &amp; baklava</strong>","Habibi Süßigkeiten","Served fresh, with strong coffee."],
   ],
   "cap":"Ratings and review counts are from our own first-party dataset on each business's real page."},
  {"t":"h2","text":"Where döner and currywurst fit in"},
  {"t":"p","html":"Sonnenallee is the deep cut, but it's part of Berlin's wider street-food identity, not apart from it. <strong>Currywurst</strong> was invented right here, by Herta Heuwer in 1949, and it's still the sentimental mascot of Berlin street food: sliced sausage, curried ketchup, done in two minutes."},
  {"t":"p","html":"<strong>Döner</strong> is the bigger story. Berlin-style döner-in-bread — meat, tomato, cucumber, cabbage and sauce folded into flatbread — is widely credited to Kadir Nurman in Kreuzberg in 1972, though the claim is genuinely disputed, with competing stories and a possible earlier Istanbul origin. Whoever invented it, döner is now Berlin's biggest-selling street food, ahead of currywurst — and Sonnenallee's shawarma shops are a close cousin of the same tradition. Order both and you'll taste the family resemblance."},
  {"t":"tip","head":"Pair it with the Türkenmarkt","html":"Neukölln's other great food institution is the <strong>Maybachufer canal-side market</strong> (the 'Türkenmarkt') — Turkish and Middle Eastern produce, cheese, bread and fabric, historically Tuesday and Friday afternoons. Confirm the day before you build a trip around it; if it lines up, it pairs naturally with a Sonnenallee afternoon."},
  {"t":"h2","text":"How to actually do the crawl"},
  {"t":"p","html":"Sonnenallee has its own S-Bahn station, or take the U7 to Karl-Marx-Straße or Rathaus Neukölln and walk in. Go in the afternoon rather than right after lunch: start with a shawarma or falafel main, walk it off past the goldsmiths, barbershops and the bridal boutique that round out the rest of the strip, then land on kunafa or warbat when you're ready. Two to three hours does it easily, and you'll still have only scratched the fifteen places above — that's rather the point. Go back."},
  {"t":"book","head":"Stay close enough to do this twice","html":"Basing yourself in Neukölln or nearby Kreuzberg puts Sonnenallee a short walk or one stop away, instead of a special trip across town.","program":"booking","query":"Neukölln Berlin","label":"See Neukölln stays on Booking"},
 ],
 "faq":[
   ("What is Sonnenallee, and why is it called Berlin's 'Arab Street'?",
    "Sonnenallee is a street through Neukölln nicknamed 'the Arab Street' by local and international press alike, including Middle East Eye and The National. Its Arab character dates to 1975, when Lebanese civil-war refugees settled North Neukölln; Syrian, Palestinian and Yemeni communities followed. Neukölln now has around 33,000 Arab residents, about a quarter of Berlin's total Arab population."),
   ("Is Sonnenallee walkable as a food crawl?",
    "Yes — that's what makes it work. Almost every business here sits directly on Sonnenallee or within a two-block walk. You can genuinely do shawarma, falafel, sweets and a market stop in one afternoon on foot, no transit needed once you're there."),
   ("What's the one thing to eat if you only have time for one stop?",
    "Either the shawarma platter at Azzam Restaurant — the flagship of the street, built for sharing — or the falafel at Al Hanan, which multiple reviewers rank among the best in Europe. If you can manage two stops, pair either with kunafa at Malek Al Konafeh to finish."),
 ],
},

]
