# -*- coding: utf-8 -*-
# CHIANG MAI — flagship city. 6 deep guides + a portal hub.
# All specifics cross-checked (July 2026 research). Honest caveats kept in.

CITY = {
 "id": "chiangmai",
 "intro_blocks": [
  {"t":"lead","html":"Chiang Mai is the rare city that rewards slowing down. Three hundred temples, a walkable old town inside a 700-year-old moat, jungle and waterfalls half an hour away, and — this is the part people underrate — some of the best food in Thailand."},
  {"t":"p","html":"This is our full guide: where to sleep by neighborhood, what to actually eat, how to get here from Bangkok, and the practical stuff (scooters, SIM cards, air quality) nobody warns you about until you're already there. Start with whichever guide below matches what you're planning."},
  {"t":"h2","text":"Where to stay, in 30 seconds"},
  {"t":"p","html":"First time and want to walk to temples? Stay in the <strong>Old City</strong>. Here to work, café-hop and go out? <strong>Nimman</strong>. Honeymoon or quiet river evenings? <strong>Riverside</strong>. Long stay on a budget? <strong>Santitham</strong>. Full breakdown, with specific hostels and hotels, in the stays guide."},
  {"t":"btnrow","btns":[
     {"program":"booking","query":"Chiang Mai","label":"See Chiang Mai stays on Booking"},
  ]},
  {"t":"tip","head":"One honest heads-up: burning season","html":"From roughly late February to early April, farmers burn fields across the north and Chiang Mai's air quality can get genuinely bad (AQI 150–300+ at the March peak). It's not just haze — it's a real reason to pick different dates if you can. November to February is the sweet spot: cool, clear, and festival season."},
  {"t":"h2","text":"The four guides to read first"},
  {"t":"p","html":"Everything below goes deep on one thing each. The food guide alone is worth the trip."},
 ],
 "faq": [
  ("How many days do you need in Chiang Mai?",
   "Three to four days covers the old city, one nature or elephant day trip, and enough time to eat well. A week is better if you want to slow down, take a cooking class, or use it as a base — which is exactly what most people end up doing."),
  ("When is the best time to visit Chiang Mai?",
   "November to February — cool, dry and clear, with the Yi Peng lantern festival in November. Avoid late February to early April, which is agricultural 'burning season' when air quality drops sharply. The green season (June–October) is lush, cheap and only rains in bursts."),
  ("Is Chiang Mai good for digital nomads?",
   "It's one of the original nomad hubs — cheap, friendly, fast wifi, a huge café and coworking scene centred on the Nimman neighborhood. See our <a class='inline' href='/chiangmai/chiang-mai-digital-nomad-guide/'>digital nomad guide</a>."),
  ("Do you need a scooter in Chiang Mai?",
   "Not in the old city, which is walkable. But a scooter unlocks the temples, cafés and waterfalls in the hills. If you're not confident on two wheels, Grab and Bolt work well. Our <a class='inline' href='/chiangmai/chiang-mai-scooter-rental/'>scooter guide</a> lists verified rental shops and monthly prices."),
 ],
}

PAGES = [

# ============================================================ WHERE TO STAY
{
 "city":"chiangmai", "slug":"where-to-stay-in-chiang-mai", "order":1,
 "title":"Where to Stay in Chiang Mai: Best Areas & Hotels",
 "kicker":"Chiang Mai · Where to stay",
 "dek":"The four neighborhoods that matter, and the hostels and hotels worth booking in each — from $5 dorms to riverside splurges.",
 "description":"An honest, area-by-area guide to where to stay in Chiang Mai — Old City, Nimman, Riverside and Santitham — with specific hostels and hotels for every budget.",
 "read":"9 min", "updated":"July 2026",
 "related":["where-to-eat-in-chiang-mai","chiang-mai-digital-nomad-guide"],
 "blocks":[
  {"t":"lead","html":"Chiang Mai is small, but where you sleep changes your whole trip. The old town, the café district, the river and the budget quarter each feel like different cities. Here's who each one is for — and exactly where to book."},
  {"t":"h2","text":"The four neighborhoods, honestly"},
  {"t":"compare","head":["Area","Best for","The trade-off"],
   "rows":[
     ["<strong>Old City</strong>","First-timers, temples, walkability","Some streets are touristy; a few party hostels get noisy"],
     ["<strong>Nimman</strong>","Nomads, cafés, nightlife, shopping","Not walkable to the historic temples; pricier"],
     ["<strong>Riverside</strong>","Couples, quiet, boutique & luxury","You'll taxi/scooter to most things; Sept–Oct flood risk"],
     ["<strong>Santitham</strong>","Long stays, budget, living like a local","Few real 'hotels' — mostly guesthouses & co-living"],
   ],
   "cap":"If you only take one thing from this page: first trip → Old City. Here to work → Nimman."},
  {"t":"h2","text":"Best hostels in Chiang Mai"},
  {"t":"p","html":"Dorm beds run from about $5 to $20; a good air-conditioned dorm sits around $10–16. The scene splits cleanly into social/party and quiet/design."},
  {"t":"stays","items":[
    {"name":"Stamps Backpackers","area":"Old City · social","band":"$8–15","program":"hostelworld","query":"Stamps Backpackers Chiang Mai",
     "blurb":"The reliable social pick — nightly events, a rooftop, and an easy crowd. Come to meet people, not to sleep early."},
    {"name":"Mad Monkey","area":"Old City · party","band":"$9–16","program":"hostelworld","query":"Mad Monkey Chiang Mai",
     "blurb":"The full-throttle party hostel of the regional chain. Great fun, genuinely loud — you know what you're signing up for."},
    {"name":"The Common Hostel","area":"Old City · best all-round","band":"$11–18","program":"hostelworld","query":"The Common Hostel Chiang Mai",
     "blurb":"Our pick for most people: design-forward, sociable but calm, good pods, laptop-friendly common space. Books out early."},
    {"name":"Hostel Lullaby","area":"Old City · quiet","band":"$12–20","program":"hostelworld","query":"Hostel Lullaby Chiang Mai",
     "blurb":"For light sleepers and solo travelers who want a hostel's price without the chaos. Calm, clean, wellness-leaning."},
    {"name":"About A Bed / La Vida CNX","area":"Old City · solo-female friendly","band":"$10–18","program":"hostelworld","query":"About A Bed Chiang Mai",
     "blurb":"Frequently recommended by solo female travelers for security, cleanliness and a welcoming front desk."},
    {"name":"Nimman Nest / Bed Addict","area":"Nimman","band":"$10–17","program":"hostelworld","query":"Nimman Nest Chiang Mai",
     "blurb":"If you want to stay in the café-and-nightlife district itself rather than the old town, these are the solid hostel options."},
  ]},
  {"t":"book","head":"Compare hostels & dorm prices","html":"Hostelworld has the widest Chiang Mai hostel inventory and real traveler reviews; Booking often lists the same beds too.","program":"hostelworld","query":"Chiang Mai","label":"Browse Chiang Mai hostels"},
  {"t":"h2","text":"Best mid-range & boutique hotels"},
  {"t":"p","html":"This is where Chiang Mai shines — genuinely characterful boutique hotels for what a bland chain costs elsewhere. Expect roughly $50–130 a night."},
  {"t":"stays","items":[
    {"name":"Tamarind Village","area":"Old City","band":"$110–160","program":"booking","query":"Tamarind Village Chiang Mai",
     "blurb":"A serene Lanna-style courtyard hotel wrapped around a giant tamarind tree, right in the old town. The classic Chiang Mai boutique."},
    {"name":"Rachamankha","area":"Old City","band":"$120–180","program":"booking","query":"Rachamankha Chiang Mai",
     "blurb":"Museum-quiet, architecturally stunning, hidden behind Wat Phra Singh. For a calm, grown-up stay."},
    {"name":"U Nimman / Akyra Manor","area":"Nimman","band":"$90–170","program":"booking","query":"Akyra Manor Chiang Mai",
     "blurb":"Design hotels in the heart of the café district — rooftop bars, walkable to Maya mall and the coworking scene."},
    {"name":"Ping Nakara","area":"Riverside","band":"$130–190","program":"booking","query":"Ping Nakara Chiang Mai",
     "blurb":"A colonial-fantasy boutique on the river — fretwork balconies, a spa, and proper romance. Watch Sept–Oct river levels."},
    {"name":"De Naga","area":"Old City edge","band":"$70–110","program":"booking","query":"De Naga Hotel Chiang Mai",
     "blurb":"Reliable Lanna style at a friendlier price, on the walkable eastern edge of the moat."},
    {"name":"B2 Santitham","area":"Santitham","band":"$30–50","program":"booking","query":"B2 Santitham Chiang Mai",
     "blurb":"The one genuine 'hotel' in the budget quarter — plain but spotless, great value for a longer base."},
  ]},
  {"t":"h2","text":"If you're splurging"},
  {"t":"p","html":"Chiang Mai's top end is special. <strong>137 Pillars House</strong> (a restored teak mansion in the city) and <strong>Anantara Chiang Mai</strong> (riverside, superb spa) are the in-town icons; the <strong>Four Seasons</strong> sits among rice terraces out in Mae Rim, 30 minutes north, if you want a resort rather than a city stay."},
  {"t":"warn","head":"Don't book the Dhara Dhevi","html":"The famous palace-like Dhara Dhevi resort is <strong>not currently bookable</strong> — it's been closed and mid-limbo after fire and ownership issues. If you see it advertised as a live stay, that listing is out of date."},
  {"t":"h2","text":"When to book (and the festival trap)"},
  {"t":"ul","items":[
    "<strong>High season is November–February.</strong> Book two to four weeks ahead, more for boutique places.",
    "<strong>Yi Peng &amp; Loy Krathong</strong> (the lantern festival, mid-to-late November) sells out the whole city months in advance and prices spike. If you're coming for it, book stays before you book anything else.",
    "<strong>Riverside in September–October:</strong> the Ping River has flooded in recent years. Lovely area, just check recent reviews before committing in those months.",
    "<strong>Green season (June–October)</strong> is the cheapest and prettiest for deals — it rains hard but briefly.",
  ]},
  {"t":"book","head":"Ready to pick a place?","html":"Booking and Agoda both have deep Chiang Mai coverage (Agoda often edges it on price in Thailand). Compare the same hotel on both.","program":"agoda","query":"Chiang Mai","label":"Check Chiang Mai hotels on Agoda"},
 ],
 "faq":[
   ("Which area of Chiang Mai is best for first-time visitors?",
    "The Old City. It's inside the historic moat, walkable to the major temples and the Sunday Walking Street, and full of cafés and affordable stays. You won't need transport for most of your day."),
   ("Is it better to stay in the Old City or Nimman?",
    "Old City for temples, history and walkability; Nimman for cafés, coworking, nightlife and modern comforts. They're a 10-minute drive apart, so many people split their stay."),
   ("How much does a hotel in Chiang Mai cost?",
    "Dorms from ~$5, clean private guesthouse rooms from ~$20, characterful boutique hotels $50–130, and genuine luxury $200+. Your money goes remarkably far here compared with most of the world."),
 ],
},

# ============================================================ WHERE TO EAT
{
 "city":"chiangmai", "slug":"where-to-eat-in-chiang-mai", "order":2,
 "title":"Where to Eat in Chiang Mai: A Local Food Guide",
 "kicker":"Chiang Mai · Food",
 "dek":"Khao soi, night markets, and the Northern Thai dishes you can't get anywhere else — with the specific places worth queuing for.",
 "description":"The real Chiang Mai food guide: the best khao soi, must-try Northern Thai dishes, the night markets that matter, and where locals actually eat.",
 "read":"11 min", "updated":"July 2026",
 "related":["where-to-stay-in-chiang-mai","best-things-to-do-in-chiang-mai"],
 "blocks":[
  {"t":"lead","html":"Northern Thai food is its own world — earthier, funkier and less sweet than the Bangkok cooking most people know. Chiang Mai is where you eat it at the source. This is what to order and where to go."},
  {"t":"h2","text":"Khao soi: the dish you came for"},
  {"t":"p","html":"A coconut curry noodle soup topped with crunchy fried noodles, with pickled mustard greens, shallots and lime on the side. It's the signature dish of the north and Chiang Mai does the best in the world. Here are the spots that matter:"},
  {"t":"compare","head":["Where","Area","Why go / heads-up"],
   "rows":[
     ["<strong class='best'>Khao Soi Mae Sai</strong>","Near Chang Phueak","Our top pick — a Michelin Bib Gourmand, superb beef, and (unlike the cult spots) normal hours with no schedule traps."],
     ["Khao Soi Khun Yai","Old City north","Beloved cult spot behind a temple. Cash only, lunch only, and closed part of the week — go early."],
     ["Lung Prakit Kad Kom","Near Kad Kom","Old-school local favourite. Also cash-only and closes when it sells out."],
     ["Khao Soi Lam Duan Fah Ham","Fah Ham (riverside)","One of the oldest khao soi houses in the city — a piece of history on the river road."],
     ["Khao Soi Islam","Old City (Ban Haw)","The halal version, in the Muslim quarter by the mosque — richer, with beef and roti."],
   ],
   "cap":"If you only get one bowl: Khao Soi Mae Sai. If you want the story: pair it with Khun Yai on a morning it's open."},
  {"t":"h2","text":"The five meals to build a trip around"},
  {"t":"do","items":[
    {"name":"SP Chicken","tag":"Gai yang","blurb":"Michelin-listed rotisserie chicken by Wat Phra Singh — smoky, garlicky, unforgettable. Get there before it sells out (often by 10:30–11am)."},
    {"name":"Huen Phen","tag":"Northern Thai","blurb":"The one-stop Northern spread: sai ua sausage, nam prik ong, khao soi, gaeng hang lay. Casual by day, atmospheric by night."},
    {"name":"Cowboy Hat Lady","tag":"Khao kha moo","blurb":"The legendary stewed-pork-leg-over-rice stall (look for the cowboy hat) at Chang Phueak Gate night market. A $2 institution."},
    {"name":"Aroon Rai","tag":"Since 1957","blurb":"A canteen-priced old-timer Anthony Bourdain loved — a fine place to try gaeng hang lay (Burmese-influenced pork curry)."},
    {"name":"Tong Tem Toh","tag":"Nimman","blurb":"The go-to sit-down Northern Thai in the café district — great for a group and a spread of dishes with a beer."},
    {"name":"Free Bird Café","tag":"Vegan","blurb":"Chiang Mai is a vegetarian paradise; this social-enterprise café is a lovely, ethical intro to Northern veg cooking."},
  ]},
  {"t":"h2","text":"Northern dishes to seek out"},
  {"t":"ul","items":[
    "<strong>Sai ua</strong> — the herby Chiang Mai grilled sausage, lemongrass and kaffir lime all through it.",
    "<strong>Nam prik ong &amp; nam prik noom</strong> — a tomato-pork chilli dip and a roasted green-chilli dip, eaten with veg and sticky rice.",
    "<strong>Gaeng hang lay</strong> — rich, gingery Burmese-influenced pork curry, barely spicy, deeply savoury.",
    "<strong>Khanom jeen nam ngiao</strong> — the north's other great noodle soup, tomatoey and tangy, criminally underrated next to khao soi.",
  ]},
  {"t":"h2","text":"The night markets, ranked by why you'd go"},
  {"t":"compare","head":["Market","When","Go for"],
   "rows":[
     ["<strong>Sunday Walking Street</strong> (Ratchadamnoen)","Sun evening","The big one — crafts and a river of street food down the old town's spine. Come hungry, come early."],
     ["<strong>Saturday Walking Street</strong> (Wualai)","Sat evening","The silver quarter's version — a touch more local, equally delicious."],
     ["<strong>Chang Phueak Gate</strong> night market","Nightly","The serious food market — home of the Cowboy Hat Lady. Less shopping, more eating."],
     ["<strong>Warorot Market</strong> (Kad Luang)","Daytime","The real deal daytime market — sai ua, dried goods, snacks, zero tourist polish."],
   ]},
  {"t":"book","head":"Learn to cook it yourself","html":"A half-day cooking class (often with a market tour and a farm visit) is one of the best-value things you can do here — around 1,000–1,500 THB. Thai Farm Cooking School is the original and still the best; Zabb E Lee is the great-value pick.","program":"gyg","query":"Chiang Mai cooking class","label":"Book a cooking class"},
  {"t":"tip","head":"Eating-well basics","html":"Most street stalls and old-school spots are <strong>cash only</strong>. The cult places keep short hours and close when they sell out, so eat khao soi at lunch, not dinner. And 'closed on the day you wanted it' is a Chiang Mai rite of passage — always have a backup."},
 ],
 "faq":[
   ("What food is Chiang Mai famous for?",
    "Khao soi — a coconut-curry noodle soup — above all, plus Northern Thai specialities like sai ua (herb sausage), nam prik dips, gaeng hang lay pork curry and khao kha moo (stewed pork leg). The cuisine is distinct from central/Bangkok Thai food."),
   ("Where is the best khao soi in Chiang Mai?",
    "Khao Soi Mae Sai is our top pick — a Michelin Bib Gourmand with excellent beef and normal opening hours. Khao Soi Khun Yai and Lung Prakit are beloved cult spots but keep short, cash-only hours."),
   ("Is Chiang Mai good for vegetarians and vegans?",
    "Exceptionally — it's one of the best cities in Asia for plant-based food, with places like Free Bird Café, Goodsouls Kitchen and Reform Kafe, plus vegetarian versions of most Northern dishes."),
 ],
},

# ============================================================ THINGS TO DO
{
 "city":"chiangmai", "slug":"best-things-to-do-in-chiang-mai", "order":3,
 "title":"Best Things to Do in Chiang Mai",
 "kicker":"Chiang Mai · Do",
 "dek":"The temples that are actually worth it, an ethical elephant day, waterfalls you can climb, and the experiences to book ahead.",
 "description":"What to do in Chiang Mai: the essential temples, ethical elephant sanctuaries, Doi Suthep, Sticky Waterfalls, markets and the tours worth booking.",
 "read":"10 min", "updated":"July 2026",
 "related":["where-to-eat-in-chiang-mai","chiang-mai-scooter-rental"],
 "blocks":[
  {"t":"lead","html":"You could fill a week here without repeating yourself. This is the honest shortlist — the sights that earn their spot, plus what to book in advance and what to just turn up for."},
  {"t":"h2","text":"The temples worth your time"},
  {"t":"p","html":"There are hundreds; you don't need to see them all. These five are the ones that stay with you:"},
  {"t":"do","items":[
    {"name":"Wat Phra That Doi Suthep","tag":"The big one","blurb":"The golden mountain temple above the city — go for sunrise or late afternoon, and for the view over Chiang Mai as much as the shrine. ~30 THB.","program":"gyg","query":"Doi Suthep Chiang Mai","label":"See Doi Suthep tours"},
    {"name":"Wat Chedi Luang","tag":"Old City","blurb":"A colossal, half-ruined 14th-century pagoda in the heart of the old town. The most atmospheric temple in the city centre.","program":None},
    {"name":"Wat Phra Singh","tag":"Old City","blurb":"The old town's most revered temple, gleaming gold and Lanna teak, lovely at dusk when the monks chant.","program":None},
    {"name":"Wat Umong","tag":"Forest & tunnels","blurb":"A 700-year-old forest temple with brick meditation tunnels and a lake, at the foot of Doi Suthep. Quiet, strange, wonderful.","program":None},
    {"name":"Wat Sri Suphan","tag":"The Silver Temple","blurb":"Entirely hand-worked in silver and aluminium in the Wualai silversmith quarter. Extraordinary up close (note: men only inside the ordination hall).","program":None},
  ]},
  {"t":"h2","text":"See elephants — the right way"},
  {"t":"p","html":"This matters, so we'll be blunt: <strong>don't ride elephants, and skip any 'sanctuary' that offers riding or circus-style shows.</strong> Choose observation-and-feeding-only ethical sanctuaries."},
  {"t":"tip","head":"The gold standard","html":"<strong>Elephant Nature Park</strong> is the original ethical sanctuary — a rescue home with no riding, where you observe and help feed. A full day runs around $77 and books out well ahead. If it's full, research any alternative carefully: 'ethical' is a marketing word as often as a real one, and even some certified parks are debated."},
  {"t":"book","head":"Book an ethical elephant day","html":"These sell out days ahead in high season. GetYourGuide and Klook both list the reputable sanctuaries with clear no-riding policies and real reviews.","program":"gyg","query":"Chiang Mai ethical elephant sanctuary","label":"See elephant sanctuary visits"},
  {"t":"h2","text":"Into the hills: nature half-days"},
  {"t":"do","items":[
    {"name":"Sticky Waterfalls (Bua Tong)","tag":"Free","blurb":"Limestone falls you can literally walk up — the rock has grip like velcro. An hour north, completely free, genuinely magic. Best with a scooter or a tour.","program":"gyg","query":"Sticky Waterfalls Chiang Mai","label":"See tours"},
    {"name":"Doi Inthanon","tag":"Thailand's roof","blurb":"The highest mountain in Thailand — twin pagodas, cloud forest, waterfalls and cool air. A full day trip, best done with a driver.","program":"gyg","query":"Doi Inthanon tour","label":"See Doi Inthanon tours"},
    {"name":"Grand Canyon Chiang Mai","tag":"Swim","blurb":"A flooded old quarry turned cliff-jump-and-swim spot with a water park. A hot-afternoon crowd-pleaser south of town.","program":None},
  ]},
  {"t":"h2","text":"Time it with a festival, if you can"},
  {"t":"p","html":"<strong>Yi Peng &amp; Loy Krathong</strong> — the lantern festival — is the most beautiful thing that happens here, when thousands of lanterns rise over the city (around November 24–25 in 2026). It's magic, it's crowded, and both accommodation and the ticketed lantern-release events book out months ahead. If your dates line up, plan around it early."},
  {"t":"book","head":"The easy wins to pre-book","html":"Cooking classes, ethical elephant days, Doi Inthanon and Sticky Waterfalls trips, and Yi Peng events are the things that sell out. Everything else you can decide on the day.","program":"klook","query":"Chiang Mai","label":"Browse Chiang Mai experiences"},
 ],
 "faq":[
   ("What are the must-see temples in Chiang Mai?",
    "Wat Phra That Doi Suthep (the mountain temple with the view), Wat Chedi Luang and Wat Phra Singh in the old city, and the atmospheric forest temple Wat Umong. The Silver Temple, Wat Sri Suphan, is also worth the trip."),
   ("Is it ethical to visit elephants in Chiang Mai?",
    "Only at genuine sanctuaries that don't allow riding or performances — Elephant Nature Park is the best-known example, focused on rescue and observation. Avoid any operation offering elephant rides or shows."),
   ("What should you book in advance in Chiang Mai?",
    "Cooking classes, ethical elephant sanctuary days, and long day trips (Doi Inthanon, Sticky Waterfalls) — plus everything if you're visiting during the November lantern festival, which sells out the city."),
 ],
},

# ============================================================ BANGKOK -> CHIANG MAI
{
 "city":"chiangmai", "slug":"bangkok-to-chiang-mai", "order":4,
 "title":"How to Get from Bangkok to Chiang Mai",
 "kicker":"Chiang Mai · Getting there",
 "dek":"Overnight sleeper train, VIP bus or a one-hour flight — the honest pros, cons and prices of each, and which to pick.",
 "description":"Train vs bus vs flight from Bangkok to Chiang Mai: real 2026 prices, journey times, and which option suits you — all bookable in one place.",
 "read":"7 min", "updated":"July 2026",
 "related":["where-to-stay-in-chiang-mai","chiang-mai-scooter-rental"],
 "blocks":[
  {"t":"lead","html":"It's about 700 km from Bangkok to Chiang Mai. You've got three good ways to cover it, and the 'best' one depends entirely on whether you value time, money or the experience itself."},
  {"t":"compare","head":["","Time","Price","Best for"],
   "rows":[
     ["<strong>Overnight train</strong>","~12–13 hrs","~$27–30","The experience + saving a night's hotel"],
     ["<strong>VIP bus</strong>","~9–11 hrs","~$15–27","Budget & frequent departures"],
     ["<strong>Flight</strong>","~1h15 + airport time","~$20–70","Saving time; often cheapest if booked early"],
   ]},
  {"t":"h2","text":"The overnight sleeper train (our sentimental pick)"},
  {"t":"p","html":"The 2nd-class air-conditioned sleeper is a proper travel experience: a made-up bunk, the north sliding past the window, breakfast as you pull in. Book the newer trains (train #9 is the most modern set) and a lower berth if you can. At ~$27–30 it also saves you a hotel night. Downside: it's slow, and berths sell out in high season — book several days ahead."},
  {"t":"h2","text":"The VIP bus (the value workhorse)"},
  {"t":"p","html":"Modern operators like <strong>Nakhonchai Air</strong> and <strong>Sombat Tour</strong> run comfortable reclining 'VIP' coaches through the day and night, from around $15. There are far more departures than trains, so it's the flexible budget option — just slightly less romantic and roughly the same duration as the train."},
  {"t":"h2","text":"Flying (when time matters)"},
  {"t":"p","html":"AirAsia, Nok Air, Thai Lion and Thai Vietjet run the route constantly; it's about 75 minutes gate to gate. Booked a few weeks out it's frequently the <em>cheapest</em> option of all (from ~$20), which surprises people. Most budget flights leave from Bangkok's Don Mueang (DMK), so factor the cross-city transfer if you're coming from the main Suvarnabhumi airport."},
  {"t":"book","head":"Book train, bus or ferry in one place","html":"12Go is the easiest way to compare and book trains, buses and flights across Thailand in English, with seat selection and instant e-tickets — much simpler than the state railway's own site.","program":"12go","target":"https://12go.asia/en/travel/bangkok/chiang-mai","label":"Check Bangkok → Chiang Mai times"},
  {"t":"tip","head":"Which should you pick?","html":"Time-rich and curious → the overnight train, every time. On a tight budget with flexible timing → the VIP bus. Short trip where a day matters → fly, and book early. All three are bookable in the same place above."},
 ],
 "faq":[
   ("What's the best way to get from Bangkok to Chiang Mai?",
    "For most travelers, the overnight 2nd-class sleeper train — it's comfortable, scenic and saves a hotel night at ~$27–30. If time is tight, a 75-minute flight is often just as cheap when booked early. VIP buses are the flexible budget option."),
   ("How long is the train from Bangkok to Chiang Mai?",
    "About 12–13 hours. The overnight sleeper leaves Bangkok in the evening and arrives in Chiang Mai the next morning, so you sleep through most of the journey."),
   ("Is it cheaper to fly or take the train to Chiang Mai?",
    "Booked a few weeks ahead, budget flights (from ~$20) can undercut the train. Last-minute, the train and bus are cheaper. Compare all three before you book."),
 ],
},

# ============================================================ SCOOTER RENTAL (crown jewel)
{
 "city":"chiangmai", "slug":"chiang-mai-scooter-rental", "order":5,
 "title":"Renting a Scooter in Chiang Mai: Verified Shops & Prices",
 "kicker":"Chiang Mai · Getting around",
 "dek":"Real rental shops we checked on the ground, honest monthly prices, and how to rent without getting stung on deposits or insurance.",
 "description":"A verified guide to renting a scooter in Chiang Mai — specific shops, real monthly prices, deposit and insurance advice, and the legal must-knows.",
 "read":"8 min", "updated":"July 2026",
 "related":["best-things-to-do-in-chiang-mai","chiang-mai-digital-nomad-guide"],
 "blocks":[
  {"t":"lead","html":"A scooter is how Chiang Mai opens up — the hill temples, the cafés down random sois, the waterfalls. Here are rental shops we actually verified (open, operating, prices from their own listings as of mid-2026), plus how to rent smart."},
  {"t":"tip","head":"Quick orientation","html":"Expect roughly <strong>฿1,500–2,500 a month</strong> for a 125cc automatic (that's about €40–66), or ฿200–300 a day short-term. A ฿1,000 cash deposit is normal — <strong>never leave your passport</strong> as deposit; leave a copy or a cash deposit instead."},
  {"t":"h2","text":"Verified rental shops"},
  {"t":"compare","head":["Shop","Monthly (125cc)","Deposit","Notes"],
   "rows":[
     ["<strong class='best'>Chiang Mai Motorbike Rentals</strong>","฿1,500–2,000","None","Cheapest we found. Monthly specialist that delivers & collects free anywhere in the city — you never visit a shop. ☎ 061 369 2358."],
     ["<strong>Mango Scooter Rentals</strong>","฿2,500","฿1,000","Best walk-in reputation — 4.8★ from ~1,500 reviews, Siri Mangkalajarn Rd Lane 1. ☎ 087 728 0515 (WhatsApp/Line)."],
     ["<strong>Zippy Motorbike Rentals</strong>","฿2,000","฿2,000","Huge review base (4.9★, ~1,400), Santitham. Prefers Facebook Messenger — message first, they reply fast."],
     ["<strong>Deer Bike</strong>","฿1,800–2,000","Varies","Long-stay expat specialist, Chang Phueak. Free hotel delivery on 2+ week rentals. FB: deerbikethailand."],
     ["<strong>Vanessa's Motorbike Hire</strong>","฿2,500","—","Legendary long-stay shop near Huay Kaew, 4.9★ from ~500 reviews. Phone or walk in. ☎ 081 020 1967."],
     ["Nimman 13","฿2,500–3,500","฿1,000","Highest-rated big shop on the Nimman/Suthep side (4.9★, ~1,140) — honest owner, clean helmets, fast deposit returns."],
   ],
   "cap":"Prices verified against the shops' own listings, July 2026. Always confirm the current monthly rate when you message — low season (roughly June–October) is negotiable."},
  {"t":"h2","text":"How to rent without regrets"},
  {"t":"ol","items":[
    "<strong>Inspect and video the bike at handover</strong> — walk around filming every scratch before you ride off, so a pre-existing dent isn't billed to you later.",
    "<strong>Check the brakes, lights, horn and tyres</strong> on the spot, and that the seat storage locks.",
    "<strong>Always wear the helmet.</strong> Police checkpoints are common and fine helmet-less riders; more importantly, it's your head.",
    "<strong>Leave a cash deposit, not your passport.</strong> A reputable shop is fine with cash or a passport copy.",
    "<strong>Get an International Driving Permit before you travel.</strong> Legally you need one (with the motorcycle category) to ride here, and travel insurance won't pay a medical claim if you were riding illegally or without a helmet.",
  ]},
  {"t":"warn","head":"The insurance catch nobody mentions","html":"Most travel-insurance motorbike cover — including SafetyWing's — <strong>only applies to engines up to 50cc</strong>, but nearly every scooter you'll rent here is 110–125cc. Read your policy's motorbike clause before you ride, carry the right licence/IDP, and never ride without a helmet, or a claim can be denied. Ride within your ability; the mountain roads are not the place to learn."},
  {"t":"book","head":"Sort travel insurance before you ride","html":"If you're going to be on two wheels (or here a while), have proper cover in place. SafetyWing is the popular nomad-friendly option — just confirm exactly what its motorbike clause covers for your engine size and licence.","program":"safetywing","label":"See SafetyWing cover"},
  {"t":"p","html":"Not confident riding? You don't need to. The old city is walkable, and <strong>Grab</strong> and <strong>Bolt</strong> (ride-hailing apps) are cheap and everywhere. A scooter just makes the hills easier."},
 ],
 "faq":[
   ("How much does it cost to rent a scooter in Chiang Mai?",
    "Roughly ฿1,500–2,500 per month (about €40–66) for a 125cc automatic, or ฿200–300 per day short-term, usually with a ฿1,000 refundable deposit. Monthly-specialist shops that deliver to your door are often the cheapest."),
   ("Do I need a licence to rent a scooter in Chiang Mai?",
    "Legally, yes — an International Driving Permit with the motorcycle category, plus your home licence. Many shops rent without checking, but riding uninsured/unlicensed voids travel-insurance medical claims and risks a police fine, so get the IDP before you travel."),
   ("Is it safe to ride a scooter in Chiang Mai?",
    "In town, with a helmet and some care, it's manageable and very common. The risks are real though — traffic, mountain roads and the insurance/licence catch above. If you're a nervous rider, use Grab or Bolt instead; the city works fine without a scooter."),
 ],
},

# ============================================================ DIGITAL NOMAD
{
 "city":"chiangmai", "slug":"chiang-mai-digital-nomad-guide", "order":6,
 "title":"Chiang Mai Digital Nomad Guide",
 "kicker":"Chiang Mai · Work & stay",
 "dek":"Where to live, work and café-hop in one of the world's original remote-work hubs — plus SIMs, insurance and the season to avoid.",
 "description":"A practical Chiang Mai digital nomad guide: best neighborhoods, coworking spaces, laptop-friendly cafés, cost of living, eSIMs and insurance.",
 "read":"9 min", "updated":"July 2026",
 "related":["where-to-stay-in-chiang-mai","chiang-mai-scooter-rental"],
 "blocks":[
  {"t":"lead","html":"Chiang Mai has been a remote-work capital for over a decade, and it's easy to see why: fast wifi, a huge café culture, a ready-made community, and a cost of living that lets you actually save. Here's how to set up."},
  {"t":"h2","text":"Where to base yourself"},
  {"t":"p","html":"<strong>Nimman</strong> is the nomad heartland — cafés, coworking, restaurants and nightlife in walking distance, and short-term condos with pools and gyms. If you want it cheaper and more local, <strong>Santitham</strong> is right next door and a fraction of the price. The Old City works too, but it's more tourist-facing. Book a week somewhere central first, then find a monthly condo once you're on the ground."},
  {"t":"book","head":"Find a monthly-friendly place","html":"For a first week while you flat-hunt, book something central and cancellable. Agoda and Booking both list Chiang Mai condos and aparthotels with weekly/monthly rates.","program":"agoda","query":"Nimman Chiang Mai","label":"See Nimman stays"},
  {"t":"h2","text":"Coworking spaces"},
  {"t":"do","items":[
    {"name":"CAMP at Maya","tag":"Free-ish","blurb":"A vast café-coworking on top of the Maya mall — free to sit, you just buy drinks (and a code unlocks wifi). Best city view and the easy default.","program":None},
    {"name":"Punspace","tag":"Serious focus","blurb":"Two quiet, 24-hour locations (Nimman and Tha Phae) built for deep work — from ~289 THB/day. The pick when you need to actually ship.","program":None},
    {"name":"Yellow Coworking","tag":"Community","blurb":"A long-standing, sociable Nimman-area space with events and a reliable members' crowd — good for meeting people.","program":None},
  ]},
  {"t":"h2","text":"Laptop-friendly cafés"},
  {"t":"p","html":"Chiang Mai's café scene is world-class and genuinely work-friendly. <strong>Ristr8to</strong> (award-winning coffee), <strong>Graph</strong> (tiny and cult), and <strong>The Barn</strong> are reliable Nimman favourites. Rotate a few — even the great cafés appreciate you not camping on one table for eight hours."},
  {"t":"h2","text":"The practical setup"},
  {"t":"ul","items":[
    "<strong>Connectivity:</strong> grab an eSIM before you land so you're online at the airport, then decide on a local SIM once you're settled. An eSIM is the zero-hassle option for the first week.",
    "<strong>Cost of living:</strong> comfortable is roughly $900–1,400/month (condo, eating out often, coworking); frugal can dip well under that.",
    "<strong>Insurance:</strong> if you're working abroad long-term, get proper travel-medical cover — and if you'll ride a scooter, re-read the engine-size clause (see our <a class='inline' href='/chiangmai/chiang-mai-scooter-rental/'>scooter guide</a>).",
    "<strong>Visas:</strong> rules change often — check the official Thai e-Visa site for the current tourist-entry and any remote-work options rather than trusting a blog (including this one) on the specifics.",
  ]},
  {"t":"btnrow","btns":[
    {"program":"airalo","query":"thailand","label":"Get a Thailand eSIM (Airalo)"},
    {"program":"safetywing","label":"Nomad insurance (SafetyWing)","style":"btn-forest"},
  ]},
  {"t":"warn","head":"Plan around burning season","html":"February to April is agricultural burning season and Chiang Mai's air quality can hit genuinely unhealthy levels (AQI 150–300+ in March). Many long-termers simply leave for those weeks. If you're choosing when to base here, aim for roughly October to January."},
 ],
 "faq":[
   ("Is Chiang Mai still good for digital nomads in 2026?",
    "Yes — it remains one of the best-value remote-work bases in the world, with fast wifi, deep café and coworking scenes, an established community and low costs. The main caveat is the Feb–Apr burning season, when many nomads temporarily leave."),
   ("How much does it cost to live in Chiang Mai as a nomad?",
    "A comfortable month — central condo, coworking, eating out regularly — runs roughly $900–1,400. Living more like a local in Santitham can bring that well below $900."),
   ("What's the best area in Chiang Mai for remote work?",
    "Nimman (Nimmanhaemin) is the nomad hub, with coworking, cafés and condos in walking distance. Santitham next door is cheaper and more local. Both beat the more tourist-oriented Old City for working."),
 ],
},

]
