# -*- coding: utf-8 -*-
# PALERMO — street-food capital. 1 deep food guide + a premium hub.
# All specifics from our own 20-business Palermo roster + web research (July 2026).

CITY = {
 "id": "palermo",
 "intro_blocks": [
  {"t":"lead","html":"Palermo is one of the world's great street-food cities — arancine, pane e panelle, sfincione, the famous spleen sandwich, all sold from carts and market stalls that have barely changed the recipe in a century. Wrap that in Arab-Norman history dense enough to earn its own UNESCO listing, and you've got one of Europe's most underrated city breaks."},
  {"t":"p","html":"Three market quarters carry that reputation: <strong>Ballarò</strong>, the biggest and most chaotic, running daily through the Albergheria district; <strong>Vucciria</strong>, half fading fish market and half open-air food-and-drinks scene once the sun goes down; and <strong>Capo</strong>, the quieter, more residential version behind the Cathedral. Everything below is built around them — where to eat first, where to sleep, what to see, and how to get in from the airport."},
  {"t":"h2","text":"Where to eat first"},
  {"t":"eats","ranked":True,"items":[
    {"name":"Osteria Mercede","slug":"osteria-mercede","area":"Politeama",
     "blurb":"Our flagship pick — a Michelin Guide-listed osteria di mare with a chalkboard-only menu built on whatever the morning market brought in, from a raw crudo platter to a grouper-and-shellfish guazzetto."},
    {"name":"Mamma Lina","slug":"mamma-lina","area":"Vucciria edge",
     "blurb":"An old-school friggitoria e gastronomia run by chef Rita. No printed prices — just ask what's frying off the handwritten bilingual board."},
    {"name":"Antonello Street Food – Arancine","slug":"antonello-arancine","area":"Ballarò/Capo",
     "blurb":"A street cart doing arancine con carne or con burro at €1.50, fried to order. The 'mignon' minis let you taste two fillings in one stop."},
    {"name":"Sicily Street Food","slug":"sicily-street-food","area":"Ballarò",
     "blurb":"A genuine seafood trattoria inside the market — the pasta con le cozze (€14) is the house special, and the frittura del giorno covers the rest of the catch."},
    {"name":"Friggitoria Chiluzzo","slug":"friggitoria-chiluzzo","area":"Kalsa",
     "blurb":"Frying pane e panelle on Piazza della Kalsa since 1943. The whole board runs from €1.50 panelle up to a €3 porchetta panino."},
    {"name":"Trattoria Al Sorriso","slug":"trattoria-al-sorriso","area":"Capo edge",
     "blurb":"Window-menu classics — grilled calamaro, a caponata starter — at prices that still feel like a market canteen."},
    {"name":"Trattoria Trapani","slug":"trattoria-trapani","area":"By Palermo Centrale station",
     "blurb":"Gamberoni alla griglia or spaghetti alle vongole — the two dishes commuters detour for before or after the train."},
  ]},
  {"t":"p","html":"That's the shortlist. For the full crawl — fifteen places, the street-food classics explained, and the three markets broken down one by one — see our <a class='inline' href='/palermo/where-to-eat-in-palermo/'>Palermo food guide</a>."},
  {"t":"h2","text":"Where to stay"},
  {"t":"p","html":"First time and want to be inside the galleries-and-palazzi quarter? Stay in <strong>Kalsa</strong>. Want a walkable base near Teatro Massimo and the Quattro Canti? Stay around <strong>Via Maqueda</strong> or the Cassaro. Prefer Palermo's polished 19th-century boulevard side — and to be steps from our flagship restaurant? <strong>Politeama/Libertà</strong>."},
  {"t":"stays","items":[
    {"name":"A Casa di Amici","area":"Libertà/Politeama","band":"€25–90","program":"booking","query":"A Casa di Amici Palermo",
     "blurb":"A boutique hostel with 7 private themed rooms plus dorms (one women-only), steps from Teatro Politeama. Breakfast included."},
    {"name":"Skyline Boutique Hotel","area":"Ruggero Settimo","band":"€60–100","program":"booking","query":"Skyline Boutique Hotel Palermo",
     "blurb":"9.0/10 on Booking — near the Via della Libertà shopping strip and the Politeama theatre."},
    {"name":"Massimo Plaza Hotel","area":"Via Maqueda, opposite Teatro Massimo","band":"€110–170","program":"booking","query":"Massimo Plaza Hotel Palermo",
     "blurb":"11 soundproofed rooms marketed as 'a window on Teatro Massimo' — genuinely across the street from the opera house."},
    {"name":"Palazzo Cartari","area":"Kalsa","band":"€100–160","program":"booking","query":"Palazzo Cartari Palermo",
     "blurb":"9.3/10 on Booking — a historic palazzo conversion inside the Kalsa quarter's gallery-and-palazzo streets."},
    {"name":"Palazzo Lanza Tomasi (Butera 28)","area":"Kalsa/Foro Italico seafront","band":"€180–320","program":"booking","query":"Butera 28 Palazzo Lanza Tomasi Palermo",
     "blurb":"Self-catering apartments inside the 18th-century palazzo that was Giuseppe Tomasi di Lampedusa's last home — his library and manuscripts are still on site."},
  ]},
  {"t":"btnrow","btns":[
     {"program":"booking","query":"Palermo","label":"See Palermo stays on Booking"},
  ]},
  {"t":"h2","text":"What to do"},
  {"t":"p","html":"Beyond the markets, this is the shortlist that earns its place:"},
  {"t":"do","items":[
    {"name":"Palermo Cathedral","tag":"UNESCO Arab-Norman","program":None,
     "blurb":"A Norman-Arab-Gothic-Baroque mashup that somehow works — royal tombs, an 1801 astronomical meridian, and the golden Crown of Constance of Sicily in the treasury."},
    {"name":"Palatine Chapel, Norman Palace","tag":"Byzantine gold mosaics","program":"gyg","query":"Palermo Royal Palace Palatine Chapel","label":"See tickets",
     "blurb":"The royal chapel inside the Norman Palace — Byzantine mosaics and an Islamic muqarnas ceiling in one small, jaw-dropping room. Part of the same UNESCO listing as the Cathedral."},
    {"name":"Teatro Massimo","tag":"Italy's largest opera house","program":"gyg","query":"Teatro Massimo Palermo tour","label":"See tours",
     "blurb":"Famed for its acoustics — guided tours run even on days with no performance."},
    {"name":"Ballarò & Vucciria markets","tag":"The street-food capital","program":"gyg","query":"Palermo street food tour Ballaro Vucciria","label":"See food tours",
     "blurb":"The two quarters that built Palermo's reputation — walk them yourself at any hour, or join a guided food crawl through both."},
    {"name":"Capuchin Catacombs","tag":"Genuinely macabre","program":"gyg","query":"Capuchin Catacombs Palermo tickets","label":"Book tickets",
     "blurb":"Around 8,000 mummified bodies, including the famously preserved child Rosalia Lombardo. No photography, and not for everyone — but unforgettable."},
    {"name":"Mondello beach","tag":"Belle Époque seaside","program":None,
     "blurb":"Palermo's sandy bay resort, reached through La Favorita park — the easy half-day escape from the historic center's stone and heat."},
  ]},
  {"t":"callout","head":"Day trips worth the detour","html":"<strong>Monreale Cathedral</strong> — a 12th-century Norman cathedral with 6,500 m² of gold mosaics — is just up the hill. <strong>Cefalù</strong>, a beach town with its own Norman cathedral and one of Italy's prettiest old towns, is about 70 km east. Both are easy half-or-full-day trips out of the city."},
  {"t":"btnrow","btns":[
    {"program":"gyg","query":"Monreale Cathedral tour from Palermo","label":"Monreale day trip"},
    {"program":"gyg","query":"Cefalu day trip from Palermo","label":"Cefalù day trip","style":"btn-forest"},
  ]},
  {"t":"h2","text":"Getting around"},
  {"t":"p","html":"Falcone–Borsellino airport (Punta Raisi) sits about 35 km from the city center. A train runs direct to Palermo Centrale roughly every 30 minutes, and Prestia e Comandè runs an equivalent bus shuttle if you'd rather go by road. Taxis wait outside arrivals — agree the fare first, and budget 45–60 minutes depending on traffic. Once you're in the historic core, walk: Kalsa, Vucciria, Ballarò, Capo and Quattro Canti all connect on foot, with a free Centro Storico tourist loop bus covering the rest (a 24-hour AMAT ticket runs about €4 if you need the wider bus network)."},
  {"t":"warn","head":"Don't rent a car for the city itself","html":"Wikivoyage flags Palermo driving directly as \"quite dangerous as the rules of the road are not followed.\" Narrow one-way historic-center streets, heavy scooter traffic and chaotic parking make a car more trouble than it's worth inside town — walk or bus centrally, and only rent one for day trips to Cefalù, Segesta or Monreale."},
  {"t":"btnrow","btns":[
    {"program":"airalo","query":"italy","label":"Get an Italy eSIM (Airalo)"},
    {"program":"safetywing","label":"Travel insurance (SafetyWing)","style":"btn-forest"},
  ]},
  {"t":"tip","head":"Best time to visit","html":"April–June and September–October hit the sweet spot: warm enough for the coast and day trips, markets in full swing, without August's peak heat and cruise crowds. Summer still works for a nightlife-focused trip, since the center stays lively late into the night — just note that some family-run places on our eats list close one day a week or take a summer break, so check before a special trip."},
 ],
 "faq": [
  ("How many days do you need in Palermo?",
   "Two to three days covers the historic core — the Cathedral, Quattro Canti, Teatro Massimo, and a proper crawl through Ballarò or Vucciria. Give it four to five if you want to add Mondello beach and a day trip to Monreale or Cefalù."),
  ("When is the best time to visit Palermo?",
   "Spring (April–June) and early autumn (September–October) — warm enough for the coast and day trips, markets in full swing, without August's peak heat. Summer still works well for a nightlife-focused trip, since the center stays lively late into the night; just check opening days, since some family-run kitchens close one day a week or take a summer break."),
  ("Do you need a car in Palermo?",
   "No — and we'd avoid one inside the city. The historic core is compact and walkable, and Palermo driving has a real reputation for chaos: narrow one-way streets, heavy scooter traffic and rules that aren't always followed. Rent a car only for day trips outside town, to Cefalù, Segesta or Monreale."),
 ],
}

PAGES = [

# ============================================================ WHERE TO EAT
{
 "city":"palermo", "slug":"where-to-eat-in-palermo", "order":1,
 "title":"Where to Eat in Palermo: Street Food, Markets & the Best Tables",
 "kicker":"Palermo · Food",
 "dek":"Arancine, panelle, sfincione and the three markets that built Palermo's street-food reputation — with 15 specific places worth eating at, our Michelin Guide-listed flagship included.",
 "description":"The real Palermo food guide: street-food classics, the three historic markets explained, and 15 real places to eat — from arancine carts to our Michelin Guide-listed flagship.",
 "read":"12 min", "updated":"July 2026",
 "related":[],
 "blocks":[
  {"t":"lead","html":"Palermo doesn't really have a fine-dining scene so much as it has the best street food in Italy — sold from carts and market stalls that have barely changed their recipes in a century — plus a handful of proper kitchens worth sitting down for. This is where to eat both."},
  {"t":"h2","text":"What to eat: the Palermo street-food classics"},
  {"t":"p","html":"Eight dishes to build a trip around. All of them are cheap, and all of them are best eaten standing up."},
  {"t":"ul","items":[
    "<strong>Arancine</strong> — fried, breaded rice balls in Palermo's cone shape, filled with ragù, peas and caciocavallo, or simply ham and cheese. Try them at Antonello Street Food or Il Rosticciere, both €1.50 a piece.",
    "<strong>Pane e panelle</strong> — a soft roll stuffed with fried chickpea-flour fritters, Palermo's original fast food. Friggitoria Chiluzzo has been frying them on Piazza della Kalsa since 1943.",
    "<strong>Sfincione</strong> — thick, spongy focaccia-pizza topped with tomato, onion, anchovy, breadcrumbs and caciocavallo, deliberately no mozzarella. Villena sells it for €7, right on the Quattro Canti.",
    "<strong>Pani ca meusa</strong> — the spleen sandwich: boiled-then-fried veal spleen and lung in a soft vastedda roll, served 'schettu' (plain, with lemon) or 'maritata' (with ricotta and caciocavallo). Look for the steel steam-carts around Vucciria and Ballarò.",
    "<strong>Cannoli</strong> — fried pastry tubes filled with sweetened ricotta, finished with candied fruit, pistachio or chocolate chips. Best bought fresh-filled, not pre-made, from any of the historic pasticcerie near the markets.",
    "<strong>Granita con brioche</strong> — semi-frozen almond, lemon, pistachio or coffee granita eaten with a soft brioche col tuppo bun. The classic Sicilian breakfast — every neighborhood has a bar locals swear is the best.",
    "<strong>Sarde a beccafico</strong> — sardines butterflied and stuffed with breadcrumbs, pine nuts and raisins, rolled and baked. On the menu at most traditional trattorie.",
    "<strong>Pasta con le sarde</strong> — bucatini with sardines, wild fennel, pine nuts, raisins and toasted breadcrumbs, Palermo's signature primo, and worth ordering wherever you see it chalked on a board.",
  ]},
  {"t":"h2","text":"The three markets, explained"},
  {"t":"h3","text":"Ballarò"},
  {"t":"p","html":"The city's biggest and most authentically local daily market, running through the Albergheria quarter Monday to Saturday, roughly 07:00–20:00. Less touristy and more chaotic than Vucciria, thick with street-food stalls and the everyday grocery trade — this is where <strong>Sicily Street Food</strong> and <strong>Antonello Street Food</strong> both sit."},
  {"t":"h3","text":"Vucciria"},
  {"t":"p","html":"Palermo's most storied market, centered on Piazza San Domenico and Piazza Garraffello. By day it's a fading, half-working fish and produce market with real atmosphere; by night the same alleys turn into an open-air street-food-and-drinks scene, with DJ sets hitting Piazza Garraffello on Fridays. Go once in daylight, once after dark — they're almost different places."},
  {"t":"h3","text":"Capo"},
  {"t":"p","html":"A tight market-street quarter behind the Cathedral, centered on Via Sant'Agostino. Quieter and more residential than Ballarò or Vucciria, but still a genuinely working daily produce-and-fish market — and home to <strong>Trattoria da Pino</strong>, tucked inside the market grid itself."},
  {"t":"book","head":"Want a guide instead of guessing?","html":"A guided street-food walking tour through Ballarò and Vucciria is an easy way to taste six or seven things in two hours without gambling on which stall is good today.","program":"gyg","query":"Palermo street food walking tour Ballaro Vucciria","label":"See street-food tours"},
  {"t":"h2","text":"Friggitoria, trattoria, osteria — what's the difference?"},
  {"t":"compare","head":["Type","What it means","Try"],
   "rows":[
     ["<strong>Friggitoria</strong>","A fry shop — pane e panelle, arancine, crocchè — sold by the piece, eaten standing up","Friggitoria Chiluzzo, Mamma Lina"],
     ["<strong>Street cart</strong>","No seating at all — arancine, panelle or pani ca meusa fried or boiled to order","Antonello Street Food, Il Rosticciere"],
     ["<strong>Trattoria</strong>","Casual, family-run, sit-down cooking — a spoken or printed menu, no white tablecloths","Trattoria Al Sorriso, Trattoria Trapani, Trattoria da Pino"],
     ["<strong>Osteria</strong>","A step up — more considered cooking, sometimes a proper wine list","Osteria Mercede, La Lapa"],
     ["<strong>Rosticceria</strong>","Roast-and-fry counter food built around one or two signature items","Il Rosticciere"],
   ],
   "cap":"None of these are fine dining, and that's the point — Palermo's best food has always been cooked fast, sold cheap and eaten standing up."},
  {"t":"h2","text":"15 places worth going out of your way for"},
  {"t":"p","html":"Ranked, starting with our flagship. Every one of these is real — we've eaten the menus, not just the reviews."},
  {"t":"eats","ranked":True,"items":[
    {"name":"Osteria Mercede","slug":"osteria-mercede","area":"Politeama",
     "blurb":"Our flagship: a Michelin Guide-listed osteria di mare with a chalkboard-only menu. Order the Crudo Mercede raw platter (prawns, scampi, tuna and swordfish) or whatever guazzetto the kitchen built around the morning catch."},
    {"name":"Mamma Lina","slug":"mamma-lina","area":"Vucciria edge",
     "blurb":"An old-school friggitoria e gastronomia run by chef Rita. No printed prices — just ask what's frying off the handwritten bilingual board."},
    {"name":"Antonello Street Food – Arancine","slug":"antonello-arancine","area":"Ballarò/Capo",
     "blurb":"A street cart doing arancine con carne or con burro at €1.50, fried to order. The 'mignon' minis let you taste two fillings in one stop."},
    {"name":"Sicily Street Food","slug":"sicily-street-food","area":"Ballarò",
     "blurb":"A genuine seafood trattoria inside the market. The pasta con le cozze (€14) is the house special; the frittura del giorno covers the rest of the catch."},
    {"name":"Friggitoria Chiluzzo","slug":"friggitoria-chiluzzo","area":"Kalsa, Piazza della Kalsa",
     "blurb":"Frying pane e panelle since 1943. The whole board runs €1.50 panelle up to a €3 porchetta panino."},
    {"name":"Trattoria Al Sorriso","slug":"trattoria-al-sorriso","area":"Capo edge",
     "blurb":"Window-menu classics: grilled calamaro (€9) or the caponata starter (€3), at prices that still feel like a market canteen."},
    {"name":"Trattoria Trapani","slug":"trattoria-trapani","area":"By Palermo Centrale station",
     "blurb":"Gamberoni alla griglia or spaghetti alle vongole — the two dishes commuters detour for before or after the train."},
    {"name":"Cartari Locanda","slug":"cartari-locanda","area":"Vucciria/Cassaro",
     "blurb":"Daily blackboard pasta paired with an actual wine list — Cerasuolo from €25 up to Franciacorta at €45."},
    {"name":"Il Rosticciere","slug":"il-rosticciere","area":"Ballarò/Stazione edge",
     "blurb":"The giant €1.50 arancina is the whole point: four real fillings chalked on the board, eaten standing at the counter."},
    {"name":"Carizzi d'amuri","slug":"carizzi-damuri","area":"Kalsa, Via Lungarini",
     "blurb":"Order the 'Acquario,' their boxed €27 signature seafood platter. Three-brothers-run, dinner only."},
    {"name":"Villena","slug":"villena","area":"Quattro Canti",
     "blurb":"Sfincione (€7) right on Palermo's most famous crossroads, or a €9–12 spritz if you just want to watch the piazza."},
    {"name":"Odori e Sapori al Vecchio Monte","slug":"odori-e-sapori","area":"Ballarò edge",
     "blurb":"A 'terra e mare' board that swings from a €25 piatto di mare to oysters at €3 each."},
    {"name":"No zu Totó e niputi","slug":"no-zu-toto","area":"Vucciria, Via dei Candelai",
     "blurb":"Impepata di cozze (peppered mussels) and wine by the litre (€2.50–8) — a late-kitchen, night-market kind of place. Closed Tuesdays."},
    {"name":"La Lapa – Osteria Siciliana","slug":"la-lapa","area":"The Cassaro",
     "blurb":"Pittinicchi cu sucu or slow-cooked crastagnieddu (goat) — Slow-Food-level cooking, not a budget stop (€18–28)."},
    {"name":"Trattoria da Pino","slug":"trattoria-da-pino","area":"Capo",
     "blurb":"Lunch-only 'Pranzo Operaio' (workers' lunch) with real bacheca pricing — primi €3–5, agnello €10. A time capsule that's been in print dining guides since 2004/05."},
  ]},
  {"t":"tip","head":"Eating in Palermo: the basics","html":"Most friggitorie and market stalls are cash-only, and family-run kitchens keep their own schedule — Carizzi d'amuri and No zu Totó both close Tuesdays, and August often means a summer break. Check opening hours or Instagram before a special trip, especially outside peak season."},
 ],
 "faq":[
   ("What is Palermo's most famous street food?",
    "Arancine — fried, breaded rice balls usually filled with ragù, peas and caciocavallo — are the dish most associated with the city, but pane e panelle (chickpea fritters in a bread roll) and sfincione (Palermo's thick tomato-and-onion focaccia-pizza) are just as essential."),
   ("What is pani ca meusa?",
    "Palermo's famous spleen sandwich — boiled-then-fried veal spleen and lung in a soft vastedda roll, served either 'schettu' (plain, with lemon) or 'maritata' (with ricotta and caciocavallo). It's sold from steel carts around the historic markets, and it's about as Palermo as food gets."),
   ("Ballarò or Vucciria — which market should I visit?",
    "Go to Ballarò by day for the biggest, most authentic working market — it runs Monday to Saturday and is thick with street-food stalls. Go to Vucciria in the evening, especially Friday, when the same fading fish-market alleys turn into an open-air food-and-drinks scene. Ideally, do both."),
 ],
},

]
